#!/usr/bin/env bash
# hermes-config-routes: integration check that the tracked (encrypted) config decrypts to a valid webhook
# gateway carrying the relay + osquery routes. SKIPS when it cannot decrypt (CI / no age key / non-darwin),
# mirroring test/brew-shellenv-cache-drift.sh. Replaces the deleted relay-hermes-route.yq unit test --
# the route is now captured in the encrypted config, not generated by a merge expression.
set -uo pipefail
fail() {
  echo "hermes-config-routes: FAIL -- $1" >&2
  exit 1
}
command -v chezmoi >/dev/null 2>&1 || {
  echo "hermes-config-routes: skipped (no chezmoi)"
  exit 0
}
cfg="$(chezmoi cat "$HOME/.hermes/config.yaml" 2>/dev/null || true)"
[[ -n $cfg ]] || {
  echo "hermes-config-routes: skipped (cannot decrypt -- no age key / CI)"
  exit 0
}
chk() { printf '%s' "$cfg" | yq -e "$1" >/dev/null 2>&1 || fail "$2"; }
chk '.platforms.webhook.enabled == true' "webhook not enabled"
chk '.platforms.webhook.extra.host == "127.0.0.1"' "host not 127.0.0.1"
chk '.platforms.webhook.extra.port == 8644' "port not 8644"
chk '.platforms.webhook.extra.routes | has("relay")' "relay route missing"
chk '.platforms.webhook.extra.routes | has("osquery")' "osquery route missing"
chk '.platforms.webhook.extra.routes | has("osquery-priority")' "osquery-priority route missing"
chk '(.platforms.webhook.extra.routes.relay.secret // "") != ""' "relay secret empty"
echo "hermes-config-routes: OK"
