#!/usr/bin/env bash
#
# reconcile-hosts-pin.sh - converge ONE /etc/hosts record for a MagicDNS
# fallback pin, as root.
#
#   reconcile-hosts-pin.sh <fqdn> <ip> <short>
#
# A pin is the fallback that answers for a tailnet name when MagicDNS is
# unavailable, so it must be exactly right or not there at all: a stale pin
# resolves confidently to the wrong host, which is worse than no pin.
#
# WHY THIS IS A SCRIPT AND NOT AN INLINE `sudo sh -c` STRING. It used to be one
# ~1KB single-line body with one-letter names, generated by
# .chezmoiscripts/run_onchange_after_41-macos-system-setup.sh.tmpl. Three
# reviewers independently called it the hardest artifact in the repo to
# re-review, and a fail-open loopback gate lived inside it through three review
# passes: the gate asked `grep -qE "^127\.0\.0\.1[[:space:]]"`, which a
# COMMENT-ONLY line ("127.0.0.1  # decoy") satisfies while mapping nothing. With
# the real "127.0.0.1 localhost pin" line filtered away for carrying the pin's
# owned short name, the rebuild installed a hosts file with ZERO working
# loopback records and exited 0. The question "is this line a valid loopback
# record?" only existed as a grep inside a pipeline, so nothing could test it.
# Here it is `hosts_line_is_valid_loopback_record`, one input and one answer.
#
# The runner template now renders one short, reviewable line per pin:
#
#   sudo "$tailnet_pin_helper" '<fqdn>' '<ip>' '<short>'
#
# CONVERGENCE is "exactly one line names this pin, and that line is exactly
# ip<TAB>fqdn<TAB>short". Testing only that a correct line EXISTS let a correct
# line plus a stale duplicate read as converged, leaving two lines naming the
# pin. When not converged the file is rebuilt: every line whose NAME FIELDS
# claim the fqdn OR the short name is dropped, every other line (comments and
# blanks included) is copied through with its bytes unchanged, and the one
# correct record is appended. The single difference the rebuild can make to a
# kept line is that a final line with NO terminator gains one; that
# normalization is required, or the appended record would join onto it.
#
# Field equality, never grep word boundaries: to grep, `.` and `-` end a word,
# so a -w filter also deleted pin.example.test.evil and other-pin.example.test,
# DIFFERENT hosts that merely contain the pinned name. The pin owns its short
# name too, by decision: the fallback exists to answer for BOTH names, so an
# unrelated line claiming the short name is dropped rather than left to compete
# (macOS resolution order between two such lines was not measured; ownership
# makes the ordering question moot).
#
# THE LOOPBACK GATE refuses, on stderr and nonzero, to install a rebuild with no
# valid loopback record. Note what "valid" means and what it does not: lo0
# reports netmask 0xff000000, so ALL of 127.0.0.0/8 is loopback and 127.0.0.100
# is a loopback address. It simply is not the exact 127.0.0.1 that localhost
# must map to, which is what this gate requires. A missing hosts file is refused
# the same way rather than seeded pin-only.
#
# INSTALL is atomic: chmod/chown the temp file to the target's own mode and
# owner, then rename it INTO the target path. mktemp creates the temp beside the
# target so the rename never crosses filesystems. The old `cat "$tmp" > target`
# kept the inode but TRUNCATED first, so a failure mid-write left an EMPTY
# /etc/hosts and still exited 0. The rename trades the inode away (a watcher
# pinning the vnode must re-open) for never exposing a partial file. A SYMLINKED
# target is followed to its referent and the referent is what gets replaced, so
# the operator's indirection survives and the file the resolver actually reads
# is the one that changes; metadata is read from the referent too, because a
# symlink's own mode is 0755 on macOS and means nothing.
#
# Every failure path exits nonzero, and an EXIT/HUP/INT/TERM trap removes the
# temporary file on every one of them, signals included. Under the runner's
# `set -e` a pin that cannot converge therefore fails the whole apply loudly
# instead of reporting success.
#
# bash 3.2 is the deployed interpreter (/bin/bash on macOS, and sudo's
# secure_path resolves `bash` there): no associative arrays, no mapfile.

set -euo pipefail

readonly PROGRAM_NAME="${0##*/}"

# ---------------------------------------------------------------------------
# Named constants. Nothing below buries one of these in an expression.
# ---------------------------------------------------------------------------

# The file this reconciles. The seam exists so the test suite exercises THIS
# code against a fixture instead of a copy of it extracted with string surgery,
# which is how the old suite and the old implementation were able to drift.
# `sudo` resets the environment (env_reset), so the deployed invocation cannot
# be redirected through it.
readonly DEFAULT_HOSTS_FILE=/etc/hosts
readonly HOSTS_FILE="${TAILNET_PIN_HOSTS_FILE:-$DEFAULT_HOSTS_FILE}"

# hosts(5): "A '#' indicates the beginning of a comment; characters up to the
# end of the line are not interpreted by routines which search the file."
readonly HOSTS_COMMENT_CHARACTER='#'

# hosts(5): each record is "Internet address / Official host name / Aliases",
# so an address with no name after it is not a mapping at all. That is exactly
# what the old gate accepted.
readonly HOSTS_RECORD_MINIMUM_FIELD_COUNT=2

# The address a working localhost record must map. See THE LOOPBACK GATE above
# for why the whole 127.0.0.0/8 block does not qualify.
readonly LOOPBACK_ADDRESS='127.0.0.1'

# Written between the columns of the record this script installs. hosts(5):
# "Items are separated by any number of blanks and/or tab characters."
readonly HOSTS_FIELD_SEPARATOR=$'\t'

# Characters a pin field may not contain: the ones that split one record into
# extra columns or extra LINES when the file is read, plus the comment
# character, which truncates the record. Deliberately the same set the runner
# template refuses at render time (Go's \s class plus #), so a field that
# renders can never be refused here and vice versa. Other Unicode spaces
# (vertical tab, U+00A0, U+2003) are absent on purpose: none of them splits a
# hosts record, so none of them can smuggle a column.
readonly HOSTS_COLUMN_FORBIDDEN_CHARACTERS=$' \t\n\r\f#'

# A file is converged when EXACTLY this many lines name the pin.
readonly CONVERGED_CLAIMING_LINE_COUNT=1

readonly BOOLEAN_TRUE=1
readonly BOOLEAN_FALSE=0

# Bound on how far a symlinked hosts path is followed, so a link loop refuses
# instead of spinning.
readonly MAXIMUM_SYMLINK_HOPS=8

readonly EXIT_STATUS_OK=0
readonly EXIT_STATUS_REFUSED=1
readonly EXIT_STATUS_USAGE=2

# Shells report a signal-terminated command as 128 + the signal number, and the
# trap handlers below keep that convention rather than inventing a status.
readonly SIGNAL_EXIT_STATUS_BASE=128
readonly SIGNAL_NUMBER_HUP=1
readonly SIGNAL_NUMBER_INT=2
readonly SIGNAL_NUMBER_TERM=15
readonly EXIT_STATUS_ON_HUP=$((SIGNAL_EXIT_STATUS_BASE + SIGNAL_NUMBER_HUP))
readonly EXIT_STATUS_ON_INT=$((SIGNAL_EXIT_STATUS_BASE + SIGNAL_NUMBER_INT))
readonly EXIT_STATUS_ON_TERM=$((SIGNAL_EXIT_STATUS_BASE + SIGNAL_NUMBER_TERM))

readonly EXPECTED_ARGUMENT_COUNT=3

# ---------------------------------------------------------------------------
# Reporting. The one place a message reaches the operator.
# ---------------------------------------------------------------------------

report() { # <message>
  printf '%s: %s\n' "$PROGRAM_NAME" "$*"
}

refuse() { # <message>
  printf '%s: %s\n' "$PROGRAM_NAME" "$*" >&2
  exit "$EXIT_STATUS_REFUSED"
}

# ---------------------------------------------------------------------------
# Pure predicates and accessors: one question each, no side effects, no I/O.
# Each is callable and testable on its own, which the old inline grep was not.
# ---------------------------------------------------------------------------

# The part of a hosts line a resolver actually reads, with comment text removed.
hosts_line_record_text() { # <line>
  local line=$1
  printf '%s\n' "${line%%"${HOSTS_COMMENT_CHARACTER}"*}"
}

# Is this line a record mapping exactly <address> to at least one name?
#
# Two conditions, and both matter. The line must carry at least an address and
# one name after comment stripping (the old gate skipped this, so a
# comment-only "127.0.0.1  # decoy" passed as a loopback record), and the
# address must START the line. hosts(5) permits blanks between items but says
# nothing about indenting a record, and whether mDNSResponder honours an
# indented one has not been measured here. A safety gate that guesses wrong
# installs a hosts file with no working localhost, so it under-accepts by
# design: refusing an indented record is loud and recoverable, vouching for one
# that the resolver ignores is not.
hosts_line_is_record_for_address() { # <line> <address>
  local line=$1 address=$2
  local -a fields=()
  # read -r -a splits on IFS WITHOUT globbing, so a '*' in a hosts file stays
  # literal text with no reliance on the shell's noglob state.
  read -r -a fields <<<"$(hosts_line_record_text "$line")"
  ((${#fields[@]} >= HOSTS_RECORD_MINIMUM_FIELD_COUNT)) || return 1
  [[ ${fields[0]} == "$address" ]] || return 1
  [[ $line == "$address"* ]]
}

# Is this line a record a machine can resolve localhost through?
hosts_line_is_valid_loopback_record() { # <line>
  hosts_line_is_record_for_address "$1" "$LOOPBACK_ADDRESS"
}

# Does this line claim <name> as one of its host names? Name fields are the
# columns AFTER the address, with comment text stripped. Field equality, so a
# different host whose name merely contains this one is not a claim.
hosts_line_claims_name() { # <line> <name>
  local line=$1 name=$2
  local -a fields=()
  read -r -a fields <<<"$(hosts_line_record_text "$line")"
  ((${#fields[@]} >= HOSTS_RECORD_MINIMUM_FIELD_COUNT)) || return 1
  local index
  for ((index = 1; index < ${#fields[@]}; index++)); do
    if [[ ${fields[index]} == "$name" ]]; then
      return 0
    fi
  done
  return 1
}

# Does this line claim either of the two names this pin owns?
hosts_line_is_claimed_by_pin() { # <line> <fqdn> <short>
  local line=$1 fqdn=$2 short=$3
  hosts_line_claims_name "$line" "$fqdn" || hosts_line_claims_name "$line" "$short"
}

# Is this value usable as exactly one hosts column?
is_single_hosts_column() { # <value>
  local value=$1
  [[ -n $value ]] || return 1
  [[ $value != *["$HOSTS_COLUMN_FORBIDDEN_CHARACTERS"]* ]]
}

# The one canonical record this pin converges on. A CONSTANT printf format, so
# a '%' inside pin data is data and never a directive.
pin_record_line() { # <ip> <fqdn> <short>
  printf '%s%s%s%s%s\n' \
    "$1" "$HOSTS_FIELD_SEPARATOR" "$2" "$HOSTS_FIELD_SEPARATOR" "$3"
}

# Is the file converged, given what the survey found?
pin_is_converged() { # <claiming-line-count> <desired-record-present>
  local claiming_line_count=$1 desired_record_present=$2
  [[ $claiming_line_count -eq $CONVERGED_CLAIMING_LINE_COUNT ]] &&
    [[ $desired_record_present -eq $BOOLEAN_TRUE ]]
}

# ---------------------------------------------------------------------------
# Filesystem readers. No mutation.
# ---------------------------------------------------------------------------

# Follow a symlink chain to the file it finally names. Relative link targets
# resolve against the directory of the link that holds them.
resolve_symlink_chain() { # <path>
  local path=$1 hop=0 link_target
  while [[ -L $path ]]; do
    hop=$((hop + 1))
    if ((hop > MAXIMUM_SYMLINK_HOPS)); then
      return 1
    fi
    link_target=$(readlink "$path")
    case $link_target in
      /*) path=$link_target ;;
      *) path="$(dirname "$path")/$link_target" ;;
    esac
  done
  printf '%s\n' "$path"
}

# GNU stat (-c) is tried before BSD stat (-f) because GNU's -f means
# "filesystem status" and SUCCEEDS with useless output, so a BSD-first chain
# never falls through. GNU coreutils precedes the BSD tools on PATH inside the
# nix dev shell, so the order is load-bearing there, not theoretical. -L on
# both: metadata must describe the referent, never a symlink (whose own mode is
# 0755 on macOS and carries no intent).
read_file_mode() { # <path>
  stat -L -c '%a' "$1" 2>/dev/null || stat -L -f '%Lp' "$1"
}

read_file_owner() { # <path>
  stat -L -c '%u:%g' "$1" 2>/dev/null || stat -L -f '%u:%g' "$1"
}

# DETECTION. Reports "<claiming-line-count> <desired-record-present>" and
# changes nothing.
survey_hosts_file() { # <path> <fqdn> <short> <desired-record>
  local path=$1 fqdn=$2 short=$3 desired_record=$4
  local claiming_line_count=0 desired_record_present=$BOOLEAN_FALSE line
  while IFS= read -r line || [[ -n $line ]]; do
    if hosts_line_is_claimed_by_pin "$line" "$fqdn" "$short"; then
      claiming_line_count=$((claiming_line_count + 1))
      if [[ $line == "$desired_record" ]]; then
        desired_record_present=$BOOLEAN_TRUE
      fi
    fi
  done <"$path"
  printf '%s %s\n' "$claiming_line_count" "$desired_record_present"
}

# VALIDATION.
hosts_file_has_valid_loopback_record() { # <path>
  local path=$1 line
  while IFS= read -r line || [[ -n $line ]]; do
    if hosts_line_is_valid_loopback_record "$line"; then
      return 0
    fi
  done <"$path"
  return 1
}

# ---------------------------------------------------------------------------
# Mutators.
# ---------------------------------------------------------------------------

# FILTERING. Drop every line the pin claims, copy everything else through
# unchanged, append the one correct record last.
write_reconciled_hosts_file() { # <source> <destination> <fqdn> <short> <desired-record>
  local source_path=$1 destination_path=$2 fqdn=$3 short=$4 desired_record=$5
  local line
  while IFS= read -r line || [[ -n $line ]]; do
    if ! hosts_line_is_claimed_by_pin "$line" "$fqdn" "$short"; then
      printf '%s\n' "$line"
    fi
  done <"$source_path" >"$destination_path"
  printf '%s\n' "$desired_record" >>"$destination_path"
}

# INSTALLATION. Metadata from the target, then an atomic rename onto it.
install_hosts_file_atomically() { # <source> <target>
  local source_path=$1 target_path=$2 mode owner
  mode=$(read_file_mode "$target_path")
  owner=$(read_file_owner "$target_path")
  chmod "$mode" "$source_path"
  chown "$owner" "$source_path"
  mv -f "$source_path" "$target_path"
}

# ---------------------------------------------------------------------------
# Temporary-file lifetime. A trap, not bail-only cleanup: the old body removed
# the temp on its explicit failure paths only, so a SIGTERM after mktemp left a
# mode-0600 hosts.XXXXXXXX beside the target, and the converged path ignored its
# own `rm` status and then hid the leftover behind `exit 0`.
# ---------------------------------------------------------------------------

temporary_hosts_file=

remove_temporary_hosts_file() {
  [[ -n $temporary_hosts_file ]] || return 0
  local path=$temporary_hosts_file
  temporary_hosts_file=
  [[ -e $path ]] || return 0
  if ! rm -f "$path"; then
    printf '%s: could not remove the temporary file %s; it is left behind\n' \
      "$PROGRAM_NAME" "$path" >&2
    return 1
  fi
}

# Clearing the traps first is what keeps `exit` from re-entering this handler.
finish() { # <exit-status>
  trap - EXIT HUP INT TERM
  local status=$1
  remove_temporary_hosts_file || status=$EXIT_STATUS_REFUSED
  exit "$status"
}

# ---------------------------------------------------------------------------

main() {
  # The EXIT handler needs the status at trap time, so its body stays unexpanded.
  trap 'finish "$?"' EXIT
  # shellcheck disable=SC2064  # expanding NOW is the intent: these are readonly
  # constants, and naming them here keeps the status the handler exits with
  # visible at the trap rather than buried in an unexpanded string.
  trap "finish $EXIT_STATUS_ON_HUP" HUP
  # shellcheck disable=SC2064
  trap "finish $EXIT_STATUS_ON_INT" INT
  # shellcheck disable=SC2064
  trap "finish $EXIT_STATUS_ON_TERM" TERM

  # Belt and braces for the mutating path: nothing here expands unquoted, and
  # the predicates split with `read -r -a` rather than the shell's splitting, so
  # this only matters if a future edit introduces an unquoted expansion.
  set -f

  if (($# != EXPECTED_ARGUMENT_COUNT)); then
    printf 'usage: %s <fqdn> <ip> <short>\n' "$PROGRAM_NAME" >&2
    exit "$EXIT_STATUS_USAGE"
  fi

  local fqdn=$1 ip=$2 short=$3

  # The runner template refuses these at render time. Re-checked here because
  # this script is a standalone component with its own contract, and because a
  # field that is not one column would write extra columns, or extra LINES, into
  # a file being rewritten as root.
  local field_name field_value
  for field_name in fqdn ip short; do
    case $field_name in
      fqdn) field_value=$fqdn ;;
      ip) field_value=$ip ;;
      short) field_value=$short ;;
    esac
    if ! is_single_hosts_column "$field_value"; then
      refuse "refusing to edit $HOSTS_FILE: pin $field_name is not a single hosts column"
    fi
  done

  local hosts_file
  if ! hosts_file=$(resolve_symlink_chain "$HOSTS_FILE"); then
    refuse "refusing to edit $HOSTS_FILE for $fqdn: its symlink chain does not resolve"
  fi
  if [[ ! -f $hosts_file ]]; then
    refuse "refusing to edit $HOSTS_FILE for $fqdn: the file is missing"
  fi

  local desired_record
  desired_record=$(pin_record_line "$ip" "$fqdn" "$short")

  local survey claiming_line_count desired_record_present
  survey=$(survey_hosts_file "$hosts_file" "$fqdn" "$short" "$desired_record")
  read -r claiming_line_count desired_record_present <<<"$survey"

  if pin_is_converged "$claiming_line_count" "$desired_record_present"; then
    report "MagicDNS fallback pin $fqdn already converged in $hosts_file"
    exit "$EXIT_STATUS_OK"
  fi

  temporary_hosts_file=$(mktemp "$hosts_file.XXXXXXXX")
  write_reconciled_hosts_file \
    "$hosts_file" "$temporary_hosts_file" "$fqdn" "$short" "$desired_record"

  if ! hosts_file_has_valid_loopback_record "$temporary_hosts_file"; then
    refuse "refusing to rewrite $HOSTS_FILE for $fqdn: the filtered result lost its loopback entry (no line maps $LOOPBACK_ADDRESS to a name)"
  fi

  install_hosts_file_atomically "$temporary_hosts_file" "$hosts_file"
  temporary_hosts_file=
  report "MagicDNS fallback pin $fqdn written to $hosts_file"
}

if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
  main "$@"
fi
