# User-level Nix configuration. Supplements /etc/nix/nix.conf written by the
# NixOS-maintained installer (https://github.com/NixOS/nix-installer).
#
# Determinate's installer used to enable these features automatically; the
# upstream installer leaves them off by default, so we re-enable here.

extra-experimental-features = nix-command flakes
max-jobs = auto
