#!/usr/bin/env bash
#
# Shell-foundation invariants for the rendered ~/.bashrc.
#
# Asserts the three in-scope behaviors of the brew-shellenv-cache + ledger-fix
# work:
#   1. Brew PATH/env comes from the sourced cache
#      (${XDG_CACHE_HOME:-~/.cache}/brew-shellenv.sh), regenerated by
#      run_after_44, NOT an unconditional inline `eval "$(brew shellenv)"`.
#   2. The dead `~/.bash_just_completions` source is gone (unmanaged, absent on
#      fresh machines; carapace already completes `just`).
#   3. The vestigial atuin `~/.atuin/bin/env` curl-installer guard is gone (atuin
#      is brew-managed, so the file never exists).
#
# Unit test: render dot_bashrc.tmpl and grep the result. OS-independent -- every
# asserted line is outside the darwin-only `{{ if }}` blocks, so the render is
# non-empty and the assertions hold on both darwin and linux.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SCRIPT="$REPO_ROOT/dot_bashrc.tmpl"

fail() {
  printf 'bashrc-shell-foundation: FAIL -- %s\n' "$*" >&2
  exit 1
}

command -v chezmoi >/dev/null 2>&1 || {
  printf 'SKIP: chezmoi not on PATH; cannot render dot_bashrc.tmpl\n'
  exit 0
}
[[ -f $SCRIPT ]] || fail "missing template: $SCRIPT"

home="$(mktemp -d)"
trap 'rm -rf "$home"' EXIT
rendered="$(HOME="$home" CI=1 chezmoi --source "$REPO_ROOT" execute-template --no-tty <"$SCRIPT")" ||
  fail 'chezmoi failed to render dot_bashrc.tmpl'
[[ -n ${rendered//[[:space:]]/} ]] || fail 'empty render'

# Assert on CODE, not comments: a comment that names a removed file (to document
# why it is gone) is legitimate and must not trip these checks. Strip full-line
# comments before matching.
code="$(grep -vE '^[[:space:]]*#' <<<"$rendered")"

# 1. Brew env is sourced from the regenerated cache.
grep -qF 'brew-shellenv.sh' <<<"$code" ||
  fail 'rendered bashrc does not source the brew-shellenv cache (brew-shellenv.sh)'

# 2. The dead just-completions source is gone.
if grep -qF '.bash_just_completions' <<<"$code"; then
  fail 'rendered bashrc still sources ~/.bash_just_completions (should be removed)'
fi

# 3. The vestigial atuin curl-installer env guard is gone.
if grep -qF '.atuin/bin/env' <<<"$code"; then
  fail 'rendered bashrc still sources ~/.atuin/bin/env (should be removed)'
fi

printf 'bashrc-shell-foundation: OK (brew cache sourced; dead just/atuin sources removed)\n'
