#!/usr/bin/env bash
#
# The pure predicates inside reconcile-hosts-pin.sh, each exercised on its own.
#
# WHY THIS FILE EXISTS. The reconciliation used to be a ~1KB single-line
# `sudo sh -c` body generated by the Tier-2 runner template, and its loopback
# safety gate was a grep inside a pipeline: `grep -qE "^127\.0\.0\.1[[:space:]]"`.
# A COMMENT-ONLY line ("127.0.0.1  # decoy") satisfies that pattern while
# leaving the machine no name to resolve localhost through, so a rebuild that
# filtered away the real localhost record (it carried the pin's owned short
# name) installed a hosts file where nothing named localhost, exit 0, no
# stderr. The question "is this line a valid loopback record?" could not be
# tested, because it had no name and no call site. It does now, and this suite
# pins it directly.
#
# WHERE THE EXPECTATIONS COME FROM. The interesting ones are not read off
# hosts(5), which is silent about indentation and wrong about comments. They
# come from the resolver's own parser, lookup.subproj/file_module.c in
# apple-oss-distributions/Libinfo, whose `_fsi_tokenize` was compiled verbatim
# and run over these fixtures. The reconciler's READING A HOSTS LINE header
# section records the three facts; this suite is where they bite.
#
# Behaviors pinned:
#   P1 loopback validity - address plus at least one NAME, address exactly
#                          127.0.0.1, address as the FIRST FIELD (leading
#                          blanks allowed, because the resolver skips them);
#                          comment-only, address-only, commented-out,
#                          other-address and other-family lines are NOT valid
#                          records.
#   P2 name claims       - whole-field equality after comment stripping, name
#                          fields only (an address is not a name), so a
#                          different host that merely contains the name is not
#                          a claim. Includes the CRLF decision: a CR is an
#                          ordinary name character to this script AND to the
#                          resolver, so a CRLF record claims "pin<CR>" in both
#                          and the pin leaves it alone. Widening either
#                          predicate to swallow the CR makes root delete
#                          unrelated records, so both directions are pinned.
#   P3 pin ownership     - a line claiming EITHER the fqdn or the short name is
#                          the pin's to replace.
#   P4 column shape      - what may be one hosts column, and what may not.
#   P5 record rendering  - the canonical tab-separated line, with pin data kept
#                          out of the printf format.
#   P6 convergence       - exactly one claiming line, that line exact, AND the
#                          file ending with a line terminator. The third
#                          condition is not cosmetic: Apple's `_fsi_get_line`
#                          chops the last character of every non-comment line it
#                          reads, so an unterminated final "...\tpin" record
#                          resolves as naming "pi". Only the rebuild writes a
#                          terminator, and the converged path skips the rebuild,
#                          so without this a file the resolver mis-reads was
#                          reported converged and left alone.
#   P7 symlink chains    - absolute and relative hops, and a bounded refusal.
#   P8 metadata readers  - mode and owner describe the file a path NAMES, not a
#                          symlink standing in front of it.
#   P9 seam states       - absent, set-to-a-path and SET-BUT-EMPTY are three
#                          answers, not two. An empty TAILNET_PIN_HOSTS_FILE
#                          used to resolve to the real /etc/hosts.
#   P10 unreadable input - every file walker FAILS on a source it cannot open,
#                          and none reports it as an empty file. Each walker
#                          ended in a `printf` after its loop, so the failed
#                          `done <"$path"` redirect never became the function's
#                          status: a chmod-000 hosts file surveyed as "0
#                          claiming lines" and the rebuild collapsed to the pin
#                          record alone.
#   P11 message paths    - one description of the file under edit, so a refusal
#                          and a success never name two different paths for the
#                          same operation.
#   P12 source-time purity - sourcing this library defines functions and changes
#                          no shell option in the caller, while EXECUTING it
#                          still runs under errexit, nounset and pipefail.
#   P13 record text      - the one place comment text is cut, so the divergence
#                          from the resolver has one home; indentation survives
#                          it, and a name written after a # is cut away, which
#                          is what the ownership filter's known limitation is
#                          made of.
#   P14 survey facts     - the three facts the survey reports, each pinned on
#                          its own, including whether the file ends with a line
#                          terminator. A whole-tuple assertion over one fixture
#                          would let two of the three drift.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
RECONCILE="$REPO_ROOT/dot_local/libexec/tailnet/executable_reconcile-hosts-pin.sh"

failures=0

fail() {
  printf 'tailnet-pin-hosts-predicates: FAIL -- %s\n' "$*" >&2
  failures=$((failures + 1))
}

[[ -f $RECONCILE ]] || {
  printf 'tailnet-pin-hosts-predicates: FAIL -- missing helper: %s\n' "$RECONCILE" >&2
  exit 1
}

# Sourcing runs no reconciliation: the script guards its entry point on
# BASH_SOURCE, which is the seam that lets these predicates be called at all.
# shellcheck source=/dev/null
source "$RECONCILE"

# assert_predicate <expect-true|expect-false> <label> <function> <args...>
assert_predicate() {
  local expectation=$1 label=$2
  shift 2
  if "$@"; then
    [[ $expectation == expect-true ]] ||
      fail "$label: expected FALSE, got true -- $*"
  else
    [[ $expectation == expect-false ]] ||
      fail "$label: expected TRUE, got false -- $*"
  fi
}

assert_equal() { # <expected> <actual> <label>
  [[ $1 == "$2" ]] ||
    fail "$3: expected $(printf '%q' "$1"), got $(printf '%q' "$2")"
}

tab=$'\t'
# A carriage return is an ordinary NAME character to both this script and the
# resolver, which is what the CRLF cases below turn on. It is not a field
# separator in either, so it is spelled out here rather than hidden in a literal.
carriage_return=$'\r'

# ---------- P1: is this line a valid loopback record? ------------------------
# The three that must be TRUE: a plain record, a record with aliases, and a
# record carrying trailing comment text (hosts(5) ignores from # to end of
# line, so the record before it still stands).
assert_predicate expect-true p1-tab-separated \
  hosts_line_is_valid_loopback_record "127.0.0.1${tab}localhost"
assert_predicate expect-true p1-space-separated \
  hosts_line_is_valid_loopback_record "127.0.0.1 localhost"
assert_predicate expect-true p1-with-aliases \
  hosts_line_is_valid_loopback_record "127.0.0.1${tab}localhost broadcasthost pin"
assert_predicate expect-true p1-trailing-comment \
  hosts_line_is_valid_loopback_record "127.0.0.1${tab}localhost # the usual one"

# THE NAME IS NOT REQUIRED TO BE `localhost`, and this is the assertion that
# says so. The gate exists to refuse a rebuild that leaves 127.0.0.1 mapping
# NOTHING; which name a given machine resolves localhost through is not
# knowable from here. Narrow this predicate to demand the literal name and every
# other P1 fixture still passes (they all happen to name localhost) while every
# pin on a machine whose loopback record reads "127.0.0.1 loopback my-mac" is
# refused, aborting the apply. The reconciler's THE LOOPBACK GATE section spends
# a paragraph on this; without these two cases nothing enforced it.
assert_predicate expect-true p1-name-is-not-localhost \
  hosts_line_is_valid_loopback_record "127.0.0.1${tab}loopback${tab}my-mac"
assert_predicate expect-true p1-name-is-not-localhost-indented \
  hosts_line_is_valid_loopback_record "  127.0.0.1 loopback"

# THE LIVE DEFECT. A comment-only line names nothing a machine could resolve
# localhost through. The old gate accepted it, which is how /etc/hosts could be
# installed with no working localhost at all.
#
# Measured, and NOT what this file used to claim: the resolver does parse these
# two as records, mapping 127.0.0.1 to the junk names "#" and "#localhost"
# respectively. Refusing them is right because neither maps localhost, not
# because they map nothing.
assert_predicate expect-false p1-comment-only-decoy \
  hosts_line_is_valid_loopback_record "127.0.0.1${tab}# comment-only decoy"
assert_predicate expect-false p1-comment-only-no-space \
  hosts_line_is_valid_loopback_record "127.0.0.1 #localhost"

# An address with no name at all is not a mapping either.
assert_predicate expect-false p1-address-only \
  hosts_line_is_valid_loopback_record "127.0.0.1"
assert_predicate expect-false p1-address-then-blank \
  hosts_line_is_valid_loopback_record "127.0.0.1${tab}"

# A commented-out record is comment text, not a record.
assert_predicate expect-false p1-commented-out \
  hosts_line_is_valid_loopback_record "#127.0.0.1${tab}localhost"

# 127.0.0.100 IS a loopback address (lo0 carries netmask 0xff000000, so all of
# 127.0.0.0/8 is loopback). It is simply not the exact address localhost must
# map to, which is what this predicate answers.
assert_predicate expect-false p1-other-loopback-address \
  hosts_line_is_valid_loopback_record "127.0.0.100${tab}dev.local"
assert_predicate expect-false p1-prefix-address \
  hosts_line_is_valid_loopback_record "127.0.0.10${tab}dev.local"
assert_predicate expect-false p1-ipv6-loopback \
  hosts_line_is_valid_loopback_record "::1${tab}localhost"
assert_predicate expect-false p1-address-in-name-position \
  hosts_line_is_valid_loopback_record "10.0.0.1${tab}127.0.0.1"
assert_predicate expect-false p1-blank-line \
  hosts_line_is_valid_loopback_record ""

# INDENTED RECORDS ARE HONOURED, and this suite used to pin the opposite on the
# stated grounds that the question was unmeasured. It is measured now:
# `_fsi_tokenize` skips ' ', '\t' and '\n' at the top of its token loop, so the
# skip lands before the FIRST token, and "  <tab>127.0.0.1 localhost" resolves
# exactly like the unindented line. A gate refusing one would block every pin on
# a file whose localhost works perfectly.
assert_predicate expect-true p1-indented-space \
  hosts_line_is_valid_loopback_record " 127.0.0.1${tab}localhost"
assert_predicate expect-true p1-indented-tab \
  hosts_line_is_valid_loopback_record "${tab}127.0.0.1 localhost"
assert_predicate expect-true p1-indented-mixed-run \
  hosts_line_is_valid_loopback_record "  ${tab} 127.0.0.1   localhost   broadcasthost"

# Indentation does not turn a NAME column into an address column: FIRST FIELD is
# still the rule, and it is the half of the old anchor worth keeping. The
# resolver agrees, reading this as 10.0.0.1 named "127.0.0.1".
assert_predicate expect-false p1-indented-address-in-name-position \
  hosts_line_is_valid_loopback_record "  10.0.0.1${tab}127.0.0.1"
# Nor does indentation rescue a comment-only line or a commented-out record.
assert_predicate expect-false p1-indented-comment-only \
  hosts_line_is_valid_loopback_record "  127.0.0.1${tab}# comment-only decoy"
assert_predicate expect-false p1-indented-commented-out \
  hosts_line_is_valid_loopback_record "  #127.0.0.1${tab}localhost"
# Whitespace alone is not a record.
assert_predicate expect-false p1-blanks-only \
  hosts_line_is_valid_loopback_record "  ${tab} "

# A CARRIAGE RETURN INSIDE THE ADDRESS FIELD DOES NOT MAKE A LOOPBACK RECORD,
# and this case is the guard on the gate rather than on the filter. A CR is not
# a separator here, so the first field is the 10-byte string "127.0.0.1<CR>",
# which is not the loopback address. Measured against the resolver by compiling
# `_fsi_tokenize` verbatim and running the fixture through it: it tokenizes on
# " \t" only, so its first token is "127.0.0.1<CR>" too, `inet_pton` refuses
# that, and the line is NOT A RECORD there either. A file whose only 127.0.0.1
# line is this one gives the machine no localhost at all, and the reconciler
# refuses to install over it.
#
# This is the assertion that kills the tempting CRLF "fix" of adding \r to
# HOSTS_ITEM_SEPARATOR_CHARACTERS. That set is used by BOTH predicates, so the
# edit does not only widen the ownership filter: it makes this line read as a
# valid loopback record, and the gate then vouches for a hosts file the resolver
# reads as having no localhost. Measured: with \r in the set, the reconciler
# rewrites such a file and exits 0 where it refuses today.
assert_predicate expect-false p1-carriage-return-in-address \
  hosts_line_is_valid_loopback_record "127.0.0.1${carriage_return}${tab}localhost"

# ---------- P2: does this line claim this name? ------------------------------
assert_predicate expect-true p2-official-name \
  hosts_line_claims_name "192.0.2.7${tab}pin.example.test${tab}pin" "pin.example.test"
assert_predicate expect-true p2-alias \
  hosts_line_claims_name "192.0.2.7${tab}pin.example.test${tab}pin" "pin"
assert_predicate expect-true p2-space-separated \
  hosts_line_claims_name "192.0.2.7 pin.example.test pin" "pin"

# Whole FIELDS, never grep word boundaries: to grep, `.` and `-` end a word, so
# a -w filter also deleted these DIFFERENT hosts.
assert_predicate expect-false p2-suffix-host \
  hosts_line_claims_name "203.0.113.5${tab}pin.example.test.evil${tab}evil" "pin.example.test"
assert_predicate expect-false p2-prefix-host \
  hosts_line_claims_name "203.0.113.6${tab}other-pin.example.test${tab}otherpin" "pin.example.test"
assert_predicate expect-false p2-substring-short \
  hosts_line_claims_name "10.0.0.1${tab}xpin.example.test${tab}unrelated" "pin"

# The address column is not a name column.
assert_predicate expect-false p2-address-column \
  hosts_line_claims_name "pin${tab}something" "pin"

# An indented line does not hide its claim, for the same reason it does not hide
# its record.
assert_predicate expect-true p2-indented \
  hosts_line_claims_name " ${tab}192.0.2.7${tab}pin.example.test${tab}pin" "pin"

# Commented-out lines claim nothing, and the resolver agrees: a line whose FIRST
# character is '#' is skipped whole.
assert_predicate expect-false p2-commented-out \
  hosts_line_claims_name "#192.0.2.7${tab}pin.example.test${tab}pin" "pin"

# THE KNOWN LIMITATION, pinned so it stays a documented decision rather than a
# surprise. This says only what THIS predicate answers. The resolver reads the
# same line as mapping 127.0.0.1 to the aliases "#" and "pin", so the rebuild
# keeps a line that does answer for the pin's name. The reconciler's KNOWN
# LIMITATION, A NAME INSIDE COMMENT TEXT section is the record of why the filter
# is not being widened in the pass that measured this.
assert_predicate expect-false p2-name-only-in-comment \
  hosts_line_claims_name "127.0.0.1${tab}localhost # pin" "pin"

# THE CRLF LIMITATION, pinned so it stays the decision the reconciler documents
# rather than something a later reader repairs. A record written with CRLF
# endings carries the CR into its LAST name field, and a CR is not a separator
# here, so the field is "pin<CR>" and the pin does not claim it.
#
# Unlike the comment case above, this one is NOT a divergence: measured by
# compiling Apple's `_fsi_tokenize` verbatim and running the fixtures through
# it, the resolver separates on " \t" only and reads the same field as the same
# 4-byte name "pin<CR>", so such a line answers for nothing the pin owns. Both
# readings agree, which is what makes leaving the line alone correct.
#
# These two are the false-positive guards on any future CRLF repair, and the
# cost they price is concrete. `nas.home` below is a THIRD PARTY: the resolver
# answers 10.0.0.5 for it, and the pin's names are not among the names it
# answers for. Measured, both proposed repairs (stripping a trailing CR
# per-field, and adding \r to the separator set) make this predicate TRUE, so
# the rebuild drops the line and root DELETES an unrelated record from
# /etc/hosts. Trading that for the removal of a line that answers nothing is the
# wrong direction, and the reconciler's KNOWN LIMITATION, CRLF section is the
# record of the decision.
assert_predicate expect-false p2-crlf-third-party-short-name \
  hosts_line_claims_name "10.0.0.5${tab}nas.home${tab}pin${carriage_return}" "pin"
assert_predicate expect-false p2-crlf-stale-pin-fqdn \
  hosts_line_claims_name \
  "198.51.100.1${tab}pin.example.test${carriage_return}" "pin.example.test"

# ---------- P3: is this line the pin's to replace? ---------------------------
assert_predicate expect-true p3-claims-fqdn \
  hosts_line_is_claimed_by_pin "198.51.100.1${tab}pin.example.test" "pin.example.test" "pin"
assert_predicate expect-true p3-claims-short \
  hosts_line_is_claimed_by_pin "192.168.1.5${tab}pin" "pin.example.test" "pin"
# The very line the defect deleted: localhost's own record, carrying the pin's
# owned short name. It IS the pin's to replace, which is exactly why the
# loopback gate has to be right about what is left afterwards.
assert_predicate expect-true p3-localhost-carrying-short-name \
  hosts_line_is_claimed_by_pin "127.0.0.1${tab}localhost${tab}pin" "pin.example.test" "pin"
assert_predicate expect-false p3-unrelated \
  hosts_line_is_claimed_by_pin "255.255.255.255${tab}broadcasthost" "pin.example.test" "pin"

# ---------- P13: the record text, and the divergence it encodes --------------
# Extracting the comment cut into one function concentrates the blast radius, so
# it gets its own coverage instead of being trusted through the two predicates
# that call it. Each case names which of the three measured facts it stands for.
record_text=
hosts_line_record_text record_text "127.0.0.1${tab}localhost"
assert_equal "127.0.0.1${tab}localhost" "$record_text" p13-no-comment-unchanged
hosts_line_record_text record_text "127.0.0.1${tab}localhost # the usual one"
assert_equal "127.0.0.1${tab}localhost " "$record_text" p13-trailing-comment-cut
hosts_line_record_text record_text "#127.0.0.1${tab}localhost"
assert_equal "" "$record_text" p13-commented-out-leaves-no-record
hosts_line_record_text record_text ""
assert_equal "" "$record_text" p13-empty-line
# Fact 1: indentation is data the field split handles, not something to strip
# here. Cutting it here would hide it from every test that measures it.
hosts_line_record_text record_text " ${tab}127.0.0.1 localhost"
assert_equal " ${tab}127.0.0.1 localhost" "$record_text" p13-indentation-preserved
# Fact 3, the divergence itself: the resolver would read "pin" here as an alias
# of nas.home. This cuts it, which is why the ownership filter keeps such a line.
hosts_line_record_text record_text "10.0.0.5${tab}nas.home # pin"
assert_equal "10.0.0.5${tab}nas.home " "$record_text" p13-comment-borne-name-cut
# Only the FIRST # cuts; there is no second pass over what is left.
hosts_line_record_text record_text "10.0.0.5${tab}nas.home # a # b"
assert_equal "10.0.0.5${tab}nas.home " "$record_text" p13-cuts-at-first-hash

# ---------- P4: is this value one hosts column? ------------------------------
assert_predicate expect-true p4-plain is_single_hosts_column "pin.example.test"
assert_predicate expect-true p4-leading-dash is_single_hosts_column "-eunrelated.ts.net"
assert_predicate expect-true p4-percent is_single_hosts_column "192.0.2.9%s"
# An IPv6 address is one column, and the COLONS are what a future tightening of
# the forbidden set toward "address-shaped characters only" would take out. That
# would refuse every IPv6 pin at the reconciler's own entry point, which is an
# aborted apply rather than a near miss. Pinned here as well as in the
# integration suite, so the fast gate catches it.
assert_predicate expect-true p4-ipv6-address is_single_hosts_column "2001:db8::7"
# Uppercase, a fully qualified trailing dot and an underscore are all one column
# too. None of them splits a hosts record, so none is refused here or at render.
assert_predicate expect-true p4-uppercase is_single_hosts_column "Upper.Example.Test"
assert_predicate expect-true p4-trailing-dot is_single_hosts_column "trailing.example.test."
assert_predicate expect-true p4-underscore is_single_hosts_column "under_score.example.test"
assert_predicate expect-false p4-empty is_single_hosts_column ""
assert_predicate expect-false p4-space is_single_hosts_column "pin space"
assert_predicate expect-false p4-tab is_single_hosts_column "pin${tab}space"
assert_predicate expect-false p4-newline is_single_hosts_column $'a\nb'
assert_predicate expect-false p4-carriage-return is_single_hosts_column $'a\rb'
assert_predicate expect-false p4-form-feed is_single_hosts_column $'a\fb'
assert_predicate expect-false p4-hash is_single_hosts_column "pin#note"
# Refused deliberately NOWHERE: none of these splits a hosts record, so none can
# smuggle a column, and the render-time check does not refuse them either. The
# two checks agree by construction.
assert_predicate expect-true p4-vertical-tab is_single_hosts_column $'a\vb'
assert_predicate expect-true p4-no-break-space is_single_hosts_column $'a b'

# ---------- P5: the canonical record --------------------------------------
assert_equal "192.0.2.7${tab}pin.example.test${tab}pin" \
  "$(pin_record_line "192.0.2.7" "pin.example.test" "pin")" p5-record
# The printf FORMAT is constant, so a % in the data is data. Move the data into
# the format position and this line comes out truncated instead.
assert_equal "192.0.2.9%s${tab}a.example.test${tab}s" \
  "$(pin_record_line "192.0.2.9%s" "a.example.test" "s")" p5-percent-in-data

# ---------- P6: converged? ---------------------------------------------------
# Arguments: <claiming-line-count> <desired-record-present> <ends-with-terminator>
assert_predicate expect-true p6-one-exact pin_is_converged 1 1 1
# "At least one correct line exists" is the wrong property: it reads a correct
# line plus a stale duplicate as converged and leaves two lines naming the pin.
assert_predicate expect-false p6-two-lines-one-exact pin_is_converged 2 1 1
assert_predicate expect-false p6-one-line-not-exact pin_is_converged 1 0 1
assert_predicate expect-false p6-absent pin_is_converged 0 0 1
# THE THIRD CONDITION, and the live defect it closes. A file whose correct pin
# record is its UNTERMINATED final line satisfied both of the other two, so the
# run reported "already converged" and changed nothing, while the resolver read
# that record as naming "pi": `_fsi_get_line` does
# `if (s[0] != '#') s[strlen(s) - 1] = '\0';` on whatever fgets returned, which
# eats a real character when there is no newline to eat. The rebuild is the only
# thing that writes a terminator and the converged path never reaches it, so
# without this the repair the reconciler's header promises was unreachable
# exactly where it was promised.
assert_predicate expect-false p6-exact-but-unterminated pin_is_converged 1 1 0
assert_predicate expect-false p6-unterminated-and-duplicated pin_is_converged 2 1 0

# ---------- P7: symlink chains -----------------------------------------------
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

printf 'x\n' >"$work/real"
ln -s "$work/real" "$work/absolute-link"
ln -s real "$work/relative-link"
ln -s absolute-link "$work/chained-link"
assert_equal "$work/real" "$(resolve_symlink_chain "$work/real")" p7-plain-file
assert_equal "$work/real" "$(resolve_symlink_chain "$work/absolute-link")" p7-absolute
assert_equal "$work/real" "$(resolve_symlink_chain "$work/relative-link")" p7-relative
assert_equal "$work/real" "$(resolve_symlink_chain "$work/chained-link")" p7-chained

ln -s loop-b "$work/loop-a"
ln -s loop-a "$work/loop-b"
if resolve_symlink_chain "$work/loop-a" >/dev/null 2>&1; then
  fail "p7-loop: a symlink loop must refuse, not resolve"
fi

# ---------- P8: metadata describes the referent, never the link --------------
# The install copies the target's mode and owner onto the replacement. Read
# through a symlink and you get the LINK's own metadata, which on macOS is a
# meaningless 0755, so a 0640 hosts file came back as a world-readable 0755 one.
# These readers answer for the file the path NAMES, whatever stands in front of
# it, which is a property of the readers rather than of any one call site.
chmod 640 "$work/real"
assert_equal 640 "$(read_file_mode "$work/real")" p8-mode-plain-file
assert_equal 640 "$(read_file_mode "$work/absolute-link")" p8-mode-through-link
assert_equal 640 "$(read_file_mode "$work/chained-link")" p8-mode-through-chain
assert_equal "$(read_file_owner "$work/real")" \
  "$(read_file_owner "$work/absolute-link")" p8-owner-through-link
# A symlink carries its OWN mode (0755 on macOS), so if it ever started
# reporting the referent's the assertions above would pass for the wrong reason.
# GNU stat (-c) first: without -L both forms report the link itself, and GNU's
# -f means "filesystem status" and would succeed with garbage if tried first.
link_own_mode="$(stat -c '%a' "$work/absolute-link" 2>/dev/null ||
  stat -f '%Lp' "$work/absolute-link")"
[[ $link_own_mode != 640 ]] ||
  fail "p8-link-mode-differs: the fixture link happens to carry the referent's mode, so P8 proves nothing"

# ---------- P9: the hosts-path seam has THREE states -------------------------
# `${VAR:-$DEFAULT}` gives an empty value the same answer as an absent one, so a
# caller passing an empty path silently aimed a root-owned rewrite at the real
# /etc/hosts. The classifier answers the question the refusal needs.
saved_seam_is_set=0
if [[ -n ${TAILNET_PIN_HOSTS_FILE+x} ]]; then
  saved_seam_is_set=1
  saved_seam_value=$TAILNET_PIN_HOSTS_FILE
fi

unset TAILNET_PIN_HOSTS_FILE
assert_equal "$HOSTS_FILE_SEAM_ABSENT" "$(classify_hosts_file_seam)" p9-absent
assert_equal "$DEFAULT_HOSTS_FILE" "$(configured_hosts_file_path)" p9-absent-path

TAILNET_PIN_HOSTS_FILE=""
assert_equal "$HOSTS_FILE_SEAM_EMPTY" "$(classify_hosts_file_seam)" p9-set-but-empty

TAILNET_PIN_HOSTS_FILE="$work/fixture-hosts"
assert_equal "$HOSTS_FILE_SEAM_PATH" "$(classify_hosts_file_seam)" p9-set-to-path
assert_equal "$work/fixture-hosts" "$(configured_hosts_file_path)" p9-set-to-path-value

unset TAILNET_PIN_HOSTS_FILE
if [[ $saved_seam_is_set -eq 1 ]]; then
  TAILNET_PIN_HOSTS_FILE=$saved_seam_value
  export TAILNET_PIN_HOSTS_FILE
fi

# ---------- P10: a source that cannot be OPENED is not an empty source --------
# Every walker must FAIL rather than report a count over zero lines. Skipped for
# uid 0, which reads a mode-000 file regardless and would make the fixture prove
# nothing.
if [[ $(id -u) -eq 0 ]]; then
  printf 'tailnet-pin-hosts-predicates: NOTE -- P10 skipped, running as uid 0 reads a mode-000 fixture\n'
else
  unreadable="$work/unreadable-hosts"
  printf '127.0.0.1\tlocalhost\n10.0.0.5\tnas.home\n192.0.2.7\tpin.example.test\tpin\n' \
    >"$unreadable"
  chmod 000 "$unreadable"

  survey_output=""
  if survey_output="$(survey_hosts_file "$unreadable" pin.example.test pin "x" 2>/dev/null)"; then
    fail "p10-survey: an unreadable hosts file was surveyed successfully as '$survey_output'; a source that cannot be read is not an empty one"
  fi
  [[ -z $survey_output ]] ||
    fail "p10-survey-silent: a failed survey still printed a count ('$survey_output'), which a caller reading stdout would use"

  if hosts_file_has_valid_loopback_record "$unreadable" 2>/dev/null; then
    fail "p10-loopback-gate: an unreadable file vouched for a loopback record it could not read"
  fi

  filtered="$work/filtered-hosts"
  if write_kept_hosts_lines "$unreadable" "$filtered" pin.example.test pin 2>/dev/null; then
    fail "p10-filter: an unreadable source produced a 'successful' rebuild; the result would be the pin record alone"
  fi

  # The same walkers must still SUCCEED once the source is readable, or P10
  # would pass on a helper that fails unconditionally.
  chmod 644 "$unreadable"
  assert_equal "1 0 1" \
    "$(survey_hosts_file "$unreadable" pin.example.test pin "x")" p10-control-survey
  assert_predicate expect-true p10-control-loopback \
    hosts_file_has_valid_loopback_record "$unreadable"
  if ! write_kept_hosts_lines "$unreadable" "$filtered" pin.example.test pin; then
    fail "p10-control-filter: a readable source must rebuild successfully"
  fi
  assert_equal "127.0.0.1${tab}localhost
10.0.0.5${tab}nas.home" "$(cat "$filtered")" p10-control-filter-content
fi

# ---------- P14: the three facts the survey reports ---------------------------
# "<claiming-line-count> <desired-record-present> <file-ends-with-terminator>".
# The fixtures below differ from the first one in ONE fact each, so a change to
# any single field shows up as a named failure rather than being absorbed by the
# other two.
survey_of() { # <fixture-file>
  survey_hosts_file "$1" pin.example.test pin \
    "$(pin_record_line 192.0.2.7 pin.example.test pin)"
}

printf '127.0.0.1\t%s\n192.0.2.7\tpin.example.test\tpin\n' localhost >"$work/sv-converged"
assert_equal "1 1 1" "$(survey_of "$work/sv-converged")" p14-converged

# THE LIVE DEFECT, at the level the reconciler decides on. Identical bytes to the
# fixture above minus the final newline: two of the three facts are unchanged, so
# the terminator is the only thing that can tell "the resolver reads this record
# as naming pin" apart from "the resolver reads it as naming pi".
printf '127.0.0.1\t%s\n192.0.2.7\tpin.example.test\tpin' localhost >"$work/sv-unterminated"
assert_equal "1 1 0" "$(survey_of "$work/sv-unterminated")" p14-unterminated-pin-record

# The unterminated final line is counted and compared like any other, not
# dropped. Drop it instead and this stale duplicate reads as one exact claiming
# line, so the file reports converged with the duplicate still in it.
printf '127.0.0.1\tlocalhost\n192.0.2.7\tpin.example.test\tpin\n10.0.0.9\tpin.example.test' \
  >"$work/sv-unterminated-duplicate"
assert_equal "2 1 0" "$(survey_of "$work/sv-unterminated-duplicate")" p14-unterminated-duplicate

# An unterminated final COMMENT is harmless to the resolver (the chop skips a
# line whose first character is '#') but still leaves the file unterminated, and
# "ends with a terminator" is the property the rebuild can actually guarantee.
printf '127.0.0.1\tlocalhost\n192.0.2.7\tpin.example.test\tpin\n# note' \
  >"$work/sv-unterminated-comment"
assert_equal "1 1 0" "$(survey_of "$work/sv-unterminated-comment")" p14-unterminated-comment

# Whitespace with no newline is still an unterminated final line.
printf '127.0.0.1\tlocalhost\n192.0.2.7\tpin.example.test\tpin\n  ' \
  >"$work/sv-unterminated-blanks"
assert_equal "1 1 0" "$(survey_of "$work/sv-unterminated-blanks")" p14-unterminated-blanks

# A trailing EMPTY line is terminated: the file's last byte is the newline.
printf '127.0.0.1\tlocalhost\n192.0.2.7\tpin.example.test\tpin\n\n' \
  >"$work/sv-trailing-blank-line"
assert_equal "1 1 1" "$(survey_of "$work/sv-trailing-blank-line")" p14-trailing-blank-line

# An EMPTY file has no final line to be missing a terminator, so it answers YES.
# Answering NO would route every run of one through a rebuild, which the
# loopback gate refuses anyway, turning a clear "lost its loopback entry" into a
# rebuild that never converges.
: >"$work/sv-empty"
assert_equal "0 0 1" "$(survey_of "$work/sv-empty")" p14-empty-file

# A file that is one unterminated line, and not the pin's: every field differs
# from the converged fixture.
printf '127.0.0.1\tlocalhost' >"$work/sv-only-unterminated"
assert_equal "0 0 0" "$(survey_of "$work/sv-only-unterminated")" p14-single-unterminated-line

# ---------- P12: sourcing changes nothing about the caller's shell ------------
# `set -euo pipefail` at file scope turned errexit, nounset and pipefail on in
# whatever sourced this file. A test that sources a library to reach its
# predicates must not have its own shell reconfigured underneath it, and this
# suite could never catch that because it sets the same options itself.
sourced_shell_flags="$(bash -c 'set +e +u +o pipefail; . "$1"; printf "%s\n" "$-"' _ "$RECONCILE")"
[[ $sourced_shell_flags != *e* ]] ||
  fail "p12-errexit: sourcing the reconciler turned errexit on in the caller (flags: $sourced_shell_flags)"
[[ $sourced_shell_flags != *u* ]] ||
  fail "p12-nounset: sourcing the reconciler turned nounset on in the caller (flags: $sourced_shell_flags)"
sourced_pipefail="$(bash -c 'set +e +u +o pipefail; . "$1"; set -o | grep "^pipefail"' _ "$RECONCILE")"
[[ $sourced_pipefail != *on* ]] ||
  fail "p12-pipefail: sourcing the reconciler turned pipefail on in the caller ($sourced_pipefail)"
# The control: EXECUTING it must still run with those options on, or P12 would
# pass on a script that simply dropped them.
# shellcheck disable=SC2016  # this is the reconciler's literal source text,
# matched byte for byte; expanding it here would search for something else.
grep -qxF 'if [[ ${BASH_SOURCE[0]} == "$0" ]]; then' "$RECONCILE" ||
  fail "p12-guard-shape: the reconciler no longer guards on being the entry point"
grep -qxF '  set -euo pipefail' "$RECONCILE" ||
  fail "p12-options-present: the reconciler no longer sets errexit/nounset/pipefail for its executed path"

# ---------- P11: one path description per operation --------------------------
# Refusals named the CONFIGURED path and reports named the RESOLVED one, so
# through a symlink the same operation was described with two different files
# depending on how it ended.
assert_equal "/etc/hosts" \
  "$(hosts_file_description /etc/hosts /etc/hosts)" p11-same-path
assert_equal "/etc/hosts (resolved through its symlink chain to /etc/hosts.real)" \
  "$(hosts_file_description /etc/hosts /etc/hosts.real)" p11-through-symlink

if ((failures > 0)); then
  printf 'tailnet-pin-hosts-predicates: %d assertion(s) failed\n' "$failures" >&2
  exit 1
fi
echo "tailnet-pin-hosts-predicates: OK (loopback validity including indented records and records that do not name localhost, record text, name claims, pin ownership, the CRLF decision in both directions, column shape, record rendering, convergence including the line terminator, survey facts, symlink chains, referent metadata, seam states, unreadable sources, source-time shell-option isolation, message paths)"
