#!/usr/bin/env bash
#
# The pure predicates inside reconcile-hosts-pin.sh, each exercised on its own.
#
# WHY THIS FILE EXISTS. The reconciliation used to be a ~1KB single-line
# `sudo sh -c` body generated by the Tier-2 runner template, and its loopback
# safety gate was a grep inside a pipeline: `grep -qE "^127\.0\.0\.1[[:space:]]"`.
# A COMMENT-ONLY line ("127.0.0.1  # decoy") satisfies that pattern while
# mapping nothing, so a rebuild that filtered away the real localhost record
# (it carried the pin's owned short name) installed a hosts file with ZERO
# working loopback records, exit 0, no stderr. The question "is this line a
# valid loopback record?" could not be tested, because it had no name and no
# call site. It does now, and this suite pins it directly.
#
# Behaviors pinned:
#   P1 loopback validity - address plus at least one NAME, address exactly
#                          127.0.0.1, address starting the line; comment-only,
#                          address-only, commented-out, other-address and
#                          other-family lines are NOT valid records.
#   P2 name claims       - whole-field equality after comment stripping, name
#                          fields only (an address is not a name), so a
#                          different host that merely contains the name is not
#                          a claim.
#   P3 pin ownership     - a line claiming EITHER the fqdn or the short name is
#                          the pin's to replace.
#   P4 column shape      - what may be one hosts column, and what may not.
#   P5 record rendering  - the canonical tab-separated line, with pin data kept
#                          out of the printf format.
#   P6 convergence       - exactly one claiming line AND that line exact.
#   P7 symlink chains    - absolute and relative hops, and a bounded refusal.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
RECONCILE="$REPO_ROOT/dot_local/libexec/tailnet/executable_reconcile-hosts-pin.sh"

failures=0

fail() {
  printf 'tailnet-pin-hosts-predicates: FAIL -- %s\n' "$*" >&2
  failures=$((failures + 1))
}

[[ -f $RECONCILE ]] || {
  printf 'tailnet-pin-hosts-predicates: FAIL -- missing helper: %s\n' "$RECONCILE" >&2
  exit 1
}

# Sourcing runs no reconciliation: the script guards its entry point on
# BASH_SOURCE, which is the seam that lets these predicates be called at all.
# shellcheck source=/dev/null
source "$RECONCILE"

# assert_predicate <expect-true|expect-false> <label> <function> <args...>
assert_predicate() {
  local expectation=$1 label=$2
  shift 2
  if "$@"; then
    [[ $expectation == expect-true ]] ||
      fail "$label: expected FALSE, got true -- $*"
  else
    [[ $expectation == expect-false ]] ||
      fail "$label: expected TRUE, got false -- $*"
  fi
}

assert_equal() { # <expected> <actual> <label>
  [[ $1 == "$2" ]] ||
    fail "$3: expected $(printf '%q' "$1"), got $(printf '%q' "$2")"
}

tab=$'\t'

# ---------- P1: is this line a valid loopback record? ------------------------
# The three that must be TRUE: a plain record, a record with aliases, and a
# record carrying trailing comment text (hosts(5) ignores from # to end of
# line, so the record before it still stands).
assert_predicate expect-true p1-tab-separated \
  hosts_line_is_valid_loopback_record "127.0.0.1${tab}localhost"
assert_predicate expect-true p1-space-separated \
  hosts_line_is_valid_loopback_record "127.0.0.1 localhost"
assert_predicate expect-true p1-with-aliases \
  hosts_line_is_valid_loopback_record "127.0.0.1${tab}localhost broadcasthost pin"
assert_predicate expect-true p1-trailing-comment \
  hosts_line_is_valid_loopback_record "127.0.0.1${tab}localhost # the usual one"

# THE LIVE DEFECT. A comment-only line has the address and then nothing the
# resolver reads. The old gate accepted it, which is how /etc/hosts could be
# installed with no working localhost at all.
assert_predicate expect-false p1-comment-only-decoy \
  hosts_line_is_valid_loopback_record "127.0.0.1${tab}# comment-only decoy"
assert_predicate expect-false p1-comment-only-no-space \
  hosts_line_is_valid_loopback_record "127.0.0.1 #localhost"

# An address with no name at all is not a mapping either.
assert_predicate expect-false p1-address-only \
  hosts_line_is_valid_loopback_record "127.0.0.1"
assert_predicate expect-false p1-address-then-blank \
  hosts_line_is_valid_loopback_record "127.0.0.1${tab}"

# A commented-out record is comment text, not a record.
assert_predicate expect-false p1-commented-out \
  hosts_line_is_valid_loopback_record "#127.0.0.1${tab}localhost"

# 127.0.0.100 IS a loopback address (lo0 carries netmask 0xff000000, so all of
# 127.0.0.0/8 is loopback). It is simply not the exact address localhost must
# map to, which is what this predicate answers.
assert_predicate expect-false p1-other-loopback-address \
  hosts_line_is_valid_loopback_record "127.0.0.100${tab}dev.local"
assert_predicate expect-false p1-prefix-address \
  hosts_line_is_valid_loopback_record "127.0.0.10${tab}dev.local"
assert_predicate expect-false p1-ipv6-loopback \
  hosts_line_is_valid_loopback_record "::1${tab}localhost"
assert_predicate expect-false p1-address-in-name-position \
  hosts_line_is_valid_loopback_record "10.0.0.1${tab}127.0.0.1"
assert_predicate expect-false p1-blank-line \
  hosts_line_is_valid_loopback_record ""

# Indented records are refused deliberately, not by accident: a safety gate
# that vouches for a record the resolver might ignore installs a hosts file
# with no working localhost, so it under-accepts.
assert_predicate expect-false p1-indented \
  hosts_line_is_valid_loopback_record " 127.0.0.1${tab}localhost"

# ---------- P2: does this line claim this name? ------------------------------
assert_predicate expect-true p2-official-name \
  hosts_line_claims_name "192.0.2.7${tab}pin.example.test${tab}pin" "pin.example.test"
assert_predicate expect-true p2-alias \
  hosts_line_claims_name "192.0.2.7${tab}pin.example.test${tab}pin" "pin"
assert_predicate expect-true p2-space-separated \
  hosts_line_claims_name "192.0.2.7 pin.example.test pin" "pin"

# Whole FIELDS, never grep word boundaries: to grep, `.` and `-` end a word, so
# a -w filter also deleted these DIFFERENT hosts.
assert_predicate expect-false p2-suffix-host \
  hosts_line_claims_name "203.0.113.5${tab}pin.example.test.evil${tab}evil" "pin.example.test"
assert_predicate expect-false p2-prefix-host \
  hosts_line_claims_name "203.0.113.6${tab}other-pin.example.test${tab}otherpin" "pin.example.test"
assert_predicate expect-false p2-substring-short \
  hosts_line_claims_name "10.0.0.1${tab}xpin.example.test${tab}unrelated" "pin"

# The address column is not a name column.
assert_predicate expect-false p2-address-column \
  hosts_line_claims_name "pin${tab}something" "pin"

# Commented-out and comment text claim nothing.
assert_predicate expect-false p2-commented-out \
  hosts_line_claims_name "#192.0.2.7${tab}pin.example.test${tab}pin" "pin"
assert_predicate expect-false p2-name-only-in-comment \
  hosts_line_claims_name "127.0.0.1${tab}localhost # pin" "pin"

# ---------- P3: is this line the pin's to replace? ---------------------------
assert_predicate expect-true p3-claims-fqdn \
  hosts_line_is_claimed_by_pin "198.51.100.1${tab}pin.example.test" "pin.example.test" "pin"
assert_predicate expect-true p3-claims-short \
  hosts_line_is_claimed_by_pin "192.168.1.5${tab}pin" "pin.example.test" "pin"
# The very line the defect deleted: localhost's own record, carrying the pin's
# owned short name. It IS the pin's to replace, which is exactly why the
# loopback gate has to be right about what is left afterwards.
assert_predicate expect-true p3-localhost-carrying-short-name \
  hosts_line_is_claimed_by_pin "127.0.0.1${tab}localhost${tab}pin" "pin.example.test" "pin"
assert_predicate expect-false p3-unrelated \
  hosts_line_is_claimed_by_pin "255.255.255.255${tab}broadcasthost" "pin.example.test" "pin"

# ---------- P4: is this value one hosts column? ------------------------------
assert_predicate expect-true p4-plain is_single_hosts_column "pin.example.test"
assert_predicate expect-true p4-leading-dash is_single_hosts_column "-eunrelated.ts.net"
assert_predicate expect-true p4-percent is_single_hosts_column "192.0.2.9%s"
assert_predicate expect-false p4-empty is_single_hosts_column ""
assert_predicate expect-false p4-space is_single_hosts_column "pin space"
assert_predicate expect-false p4-tab is_single_hosts_column "pin${tab}space"
assert_predicate expect-false p4-newline is_single_hosts_column $'a\nb'
assert_predicate expect-false p4-carriage-return is_single_hosts_column $'a\rb'
assert_predicate expect-false p4-form-feed is_single_hosts_column $'a\fb'
assert_predicate expect-false p4-hash is_single_hosts_column "pin#note"
# Refused deliberately NOWHERE: none of these splits a hosts record, so none can
# smuggle a column, and the render-time check does not refuse them either. The
# two checks agree by construction.
assert_predicate expect-true p4-vertical-tab is_single_hosts_column $'a\vb'
assert_predicate expect-true p4-no-break-space is_single_hosts_column $'a b'

# ---------- P5: the canonical record --------------------------------------
assert_equal "192.0.2.7${tab}pin.example.test${tab}pin" \
  "$(pin_record_line "192.0.2.7" "pin.example.test" "pin")" p5-record
# The printf FORMAT is constant, so a % in the data is data. Move the data into
# the format position and this line comes out truncated instead.
assert_equal "192.0.2.9%s${tab}a.example.test${tab}s" \
  "$(pin_record_line "192.0.2.9%s" "a.example.test" "s")" p5-percent-in-data

# ---------- P6: converged? ---------------------------------------------------
assert_predicate expect-true p6-one-exact pin_is_converged 1 1
# "At least one correct line exists" is the wrong property: it reads a correct
# line plus a stale duplicate as converged and leaves two lines naming the pin.
assert_predicate expect-false p6-two-lines-one-exact pin_is_converged 2 1
assert_predicate expect-false p6-one-line-not-exact pin_is_converged 1 0
assert_predicate expect-false p6-absent pin_is_converged 0 0

# ---------- P7: symlink chains -----------------------------------------------
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

printf 'x\n' >"$work/real"
ln -s "$work/real" "$work/absolute-link"
ln -s real "$work/relative-link"
ln -s absolute-link "$work/chained-link"
assert_equal "$work/real" "$(resolve_symlink_chain "$work/real")" p7-plain-file
assert_equal "$work/real" "$(resolve_symlink_chain "$work/absolute-link")" p7-absolute
assert_equal "$work/real" "$(resolve_symlink_chain "$work/relative-link")" p7-relative
assert_equal "$work/real" "$(resolve_symlink_chain "$work/chained-link")" p7-chained

ln -s loop-b "$work/loop-a"
ln -s loop-a "$work/loop-b"
if resolve_symlink_chain "$work/loop-a" >/dev/null 2>&1; then
  fail "p7-loop: a symlink loop must refuse, not resolve"
fi

if ((failures > 0)); then
  printf 'tailnet-pin-hosts-predicates: %d assertion(s) failed\n' "$failures" >&2
  exit 1
fi
echo "tailnet-pin-hosts-predicates: OK (loopback validity, name claims, pin ownership, column shape, record rendering, convergence, symlink chains)"
