bookmarks = [
  "/Users/stephen/workspaces/Ivy/Projects/Casually Concerned",
  "/Users/stephen/.local/share/chezmoi",
  "/Users/stephen/.openclaw",
]

[[search_dirs]]
path = "/Users/stephen/.config"

depth = 2
[[search_dirs]]
path = "/Users/stephen/workspaces"
depth = 2

[[search_dirs]]
path = "/Users/stephen/workspaces/Ivy/webdavis"
depth = 2

[[sessions]]
name = "uriel"
path = "/Users/stephen/workspaces/Ivy/webdavis/uriel"

[[sessions]]
name = "openclaw"
path = "/Users/stephen/.openclaw"

[[sessions]]
name = "Homelab"
path = "/Users/stephen/workspaces/Ivy/webdavis/homelab"

[marks]
0 = "/Users/stephen/workspaces/Ivy/webdavis/uriel"
1 = "/Users/stephen/.openclaw"
2 = "/Users/stephen/workspaces/Ivy/webdavis/homelab"
3 = "/Users/stephen/workspaces/Ivy"
4 = "/Users/stephen/workspaces/Ivy/Projects/Casually Concerned"
5 = "/Users/stephen/.local/share/chezmoi"
6 = "/Users/stephen/.config/nvim"
7 = "/Users/stephen/workspaces/Ivy/webdavis/essential-feed-case-study"
8 = "/Users/stephen/workspaces/Ivy/webdavis/webdavis"
9 = "/Users/stephen/workspaces/Ivy/webdavis/job-hunting"
10 = "/Users/stephen/workspaces/Ivy/webdavis/justdavis-ansible"
11 = "/Users/stephen/workspaces/Ivy/webdavis/Maeve"
