[[search_dirs]]
path = "/Users/stephen/.config"
depth = 2

[[search_dirs]]
path = "/Users/stephen/workspaces"
depth = 2

[[search_dirs]]
path = "/Users/stephen/workspaces/webdavis/projects"
depth = 2

[marks]
0 = "/Users/stephen/workspaces/webdavis/projects/mac-dev-config"
1 = "/Users/stephen/.local/share/chezmoi"
2 = "/Users/stephen/workspaces/webdavis/projects/essential-feed-case-study"
3 = "/Users/stephen/workspaces/webdavis/projects/webdavis"
4 = "/Users/stephen/workspaces/webdavis/projects/Homelab"
5 = "/Users/stephen/workspaces/Ivy"
6 = "/Users/stephen/workspaces/webdavis/projects/Maeve"
7 = "/Users/stephen/.config/nvim"
8 = "/Users/stephen/workspaces/pqi"
9 = "/Users/stephen/workspaces/webdavis/projects/docker-raspios-lite"
10 = "/Users/stephen/workspaces/webdavis/projects/sierras-macOS-backup"
