[[search_dirs]]
path = "/Users/stephen/.config"

depth = 2
[[search_dirs]]
path = "/Users/stephen/workspaces"
depth = 2

[[search_dirs]]
path = "/Users/stephen/workspaces/webdavis"
depth = 2

[marks]
0 = "/Users/stephen/workspaces/webdavis/mac-dev-config"
1 = "/Users/stephen/workspaces/Ivy/1. Casually Concerned"
2 = "/Users/stephen/.local/share/chezmoi"
3 = "/Users/stephen/workspaces/webdavis/essential-feed-case-study"
4 = "/Users/stephen/workspaces/webdavis/webdavis"
5 = "/Users/stephen/workspaces/webdavis/Homelab"
6 = "/Users/stephen/workspaces/Ivy"
7 = "/Users/stephen/workspaces/webdavis/job-hunting"
8 = "/Users/stephen/workspaces/webdavis/justdavis-ansible"
9 = "/Users/stephen/workspaces/webdavis/Maeve"
10 = "/Users/stephen/.config/nvim"
11 = "/Users/stephen/workspaces/webdavis/docker-raspios-lite"
12 = "/Users/stephen/workspaces/webdavis/sierras-macOS-backup"
