# https://github.com/agavra/tuicr/blob/main/docs/CONFIG.md
theme = "catppuccin-mocha"
compact_folders = true
show_pr_checks = true
comment_tab_width = 2
relative_line_numbers = true
wrap = true
single_file_view = true
