#!/usr/bin/env bash
#
# reconcile-hosts-pin.sh - converge ONE /etc/hosts record for a MagicDNS
# fallback pin, as root.
#
#   reconcile-hosts-pin.sh <fqdn> <ip> <short>
#
# A pin is the fallback that answers for a tailnet name when MagicDNS is
# unavailable, so it must be exactly right or not there at all: a stale pin
# resolves confidently to the wrong host, which is worse than no pin.
#
# WHY THIS IS A SCRIPT AND NOT AN INLINE `sudo sh -c` STRING. It used to be one
# ~1KB single-line body with one-letter names, generated by
# .chezmoiscripts/run_onchange_after_41-macos-system-setup.sh.tmpl. Three
# reviewers independently called it the hardest artifact in the repo to
# re-review, and a fail-open loopback gate lived inside it through three review
# passes: the gate asked `grep -qE "^127\.0\.0\.1[[:space:]]"`, which a
# COMMENT-ONLY line ("127.0.0.1  # decoy") satisfies while leaving the machine
# no name to resolve localhost through. With the real "127.0.0.1 localhost pin"
# line filtered away for carrying the pin's owned short name, the rebuild
# installed a hosts file where nothing named localhost, and exited 0. The
# question "is this line a valid loopback record?" only existed as a grep inside
# a pipeline, so nothing could test it. Here it is
# `hosts_line_is_valid_loopback_record`, one input and one answer.
#
# The runner template now renders one short, reviewable line per pin:
#
#   sudo "$tailnet_pin_helper" '<fqdn>' '<ip>' '<short>'
#
# CONVERGENCE is "exactly one line names this pin, that line is exactly
# ip<TAB>fqdn<TAB>short, and the file ENDS WITH A LINE TERMINATOR". Testing only
# that a correct line EXISTS let a correct line plus a stale duplicate read as
# converged, leaving two lines naming the pin. The terminator is the third
# condition because the rebuild is the only thing that writes one and the
# converged path never reaches the rebuild: a file whose UNTERMINATED final line
# was the pin's own record read as converged, so the run exited 0 and changed
# nothing, while the resolver read that record as naming "pi" (fact 4 below).
# Reporting success on a file the resolver reads differently from its bytes is
# the same fail-quiet this script exists to close, one door over, so a file is
# not converged until the terminator is there. When not converged the file is
# rebuilt: every line whose NAME FIELDS claim the fqdn OR the short name is
# dropped, every other line (comments and blanks included) is copied through,
# and the one correct record is appended.
#
# WHAT "COPIED THROUGH" DOES AND DOES NOT PROMISE. Two departures from byte
# fidelity, both measured, neither of them optional:
#
#   - The FINAL line of a source with no terminator gains one, and if it ended
#     with a carriage return it loses that. The terminator is required or the
#     appended record would join onto it; the carriage return goes because
#     giving it back is what would break the line. THE UNREAD CARRIAGE RETURN
#     below is the whole story, and it is not a footnote: leaving it cost the
#     machine its localhost.
#   - A line carrying a NUL byte is written back with the NUL gone and the two
#     halves joined, and nothing here can prevent that: kept lines live in shell
#     variables, and bash `read` drops a NUL silently because no shell variable
#     can hold one. Measured, "10.0.0.5<TAB>nas.home<NUL>junk" comes back as
#     "10.0.0.5<TAB>nas.homejunk". Refusing such a file outright was weighed and
#     not taken: measured with the resolver's own parser, `strlen` stops at the
#     NUL, so `_fsi_get_line`'s chop lands on the byte BEFORE it and the record
#     already read as naming "nas.hom" going in. Adding an abort path to a root
#     script to protect a name nothing could resolve is the wrong trade, so the
#     limit is stated here and pinned in LAYER 2j5 of the integration suite
#     instead. If kept lines ever stop passing through shell variables, that
#     assertion is where the promise can be widened.
#
# An installed file therefore always ends terminated, so the repair costs at
# most one rebuild and the next run converges.
#
# Field equality, never grep word boundaries: to grep, `.` and `-` end a word,
# so a -w filter also deleted pin.example.test.evil and other-pin.example.test,
# DIFFERENT hosts that merely contain the pinned name. The pin owns its short
# name too, by decision: the fallback exists to answer for BOTH names, so an
# unrelated line claiming the short name is dropped rather than left to compete
# (macOS resolution order between two such lines was not measured; ownership
# makes the ordering question moot).
#
# THE LOOPBACK GATE refuses, on stderr and nonzero, to install a rebuild with no
# valid loopback record. It runs on the lines the rebuild KEEPS, before this
# script's own record is appended to them, and that ordering is the gate: a pin
# whose ip is 127.0.0.1 (one mistyped YAML field) would otherwise be checked
# against the very line the rebuild had just written, so a hosts file whose only
# 127.0.0.1 record is the pin's own would pass the gate that exists to prevent
# exactly that file. Note what "valid" means and what it does not. lo0 reports
# netmask 0xff000000, so ALL of 127.0.0.0/8 is loopback and 127.0.0.100 is a
# loopback address; the gate wants the exact 127.0.0.1 that localhost must map
# to. It requires that address to map to at least one name written BEFORE any
# comment, and does not require the name to be `localhost`: this script has no
# way to know which name a given machine resolves localhost through, and
# refusing to vouch for a file it cannot read the intent of would be a guess in
# the unsafe direction. That latitude is load-bearing rather than decorative, so
# it is pinned twice: the unit suite asserts the predicate accepts a record that
# names something else, and the integration suite reconciles a hosts file whose
# ONLY loopback record does. Narrowing the gate to demand `localhost` refuses
# every pin on such a machine, which is an aborted `chezmoi apply`, not a near
# miss, and until those two cases existed nothing here noticed. The
# "before any comment" half is stricter than the resolver itself, deliberately;
# see READING A HOSTS LINE. A missing hosts file is refused the same way rather
# than seeded pin-only.
#
# READING A HOSTS LINE, measured against the resolver instead of assumed. The
# source is Apple's own hosts reader, lookup.subproj/file_module.c in
# apple-oss-distributions/Libinfo, and each fact below was re-verified by
# compiling its `_fsi_tokenize` verbatim and running fixtures through it rather
# than by reading it. hosts(5) is silent on the first and wrong about the
# second, so the man page is not the authority here.
#
#   1. LEADING BLANKS ARE SKIPPED, so AN INDENTED RECORD WORKS. `_fsi_tokenize`
#      runs "skip leading white space" over ' ', '\t' and '\n' at the top of its
#      token loop, which puts the skip before the FIRST token too, and
#      `_fsi_parse_host` tokenizes hosts lines with the separator set " \t".
#      Measured: "  <tab>127.0.0.1   localhost   broadcasthost" parses exactly
#      like the unindented line. The predicates here accept one. They still
#      require the address to be the FIRST FIELD, which is a different question
#      from it starting the line: "  10.0.0.1<tab>127.0.0.1" maps the NAME
#      "127.0.0.1" and is refused.
#
#   2. A '#' DOES NOT END A RECORD FOR THE RESOLVER. Only a line whose FIRST
#      character is '#' is skipped: `_fsi_get_line` strips the trailing newline
#      and nothing else, and the read loop tests `line[0] == '#'`. Anywhere else
#      a '#' is an ordinary token character. Measured: "127.0.0.1  # decoy"
#      parses as a VALID record mapping 127.0.0.1 to the official name "#" with
#      the alias "decoy", and "127.0.0.1 #localhost" maps it to the single name
#      "#localhost". Refusing those is still right, because neither gives the
#      machine `localhost`, but they do not "map nothing" and this file no
#      longer says they do.
#
#   3. THIS SCRIPT CUTS AT THE '#' ANYWAY, and that is a DIVERGENCE from the
#      resolver rather than compliance with it. `hosts_line_record_text` is the
#      one place it happens, so both predicates read the same text and a name
#      that exists only inside comment text is invisible to both. For the GATE
#      that is the safe direction: a file whose only 127.0.0.1 record names "#"
#      is refused loudly instead of vouched for. For the OWNERSHIP FILTER it is
#      the unsafe direction, recorded below as a known limitation rather than
#      pretended away.
#
#   4. THE LAST CHARACTER OF AN UNTERMINATED FINAL LINE IS EATEN, and this is
#      the fact CONVERGENCE above turns on. `_fsi_get_line` runs
#      `if (s[0] != '#') s[strlen(s) - 1] = '\0';` over whatever `fgets`
#      returned, unconditionally: on every terminated line that removes the
#      newline, and on an unterminated final line it removes a REAL character.
#      Measured: a file ending "192.0.2.7<tab>pin.example.test<tab>pin" with no
#      newline reads as naming "pi", so the pin's short name does not answer,
#      and a file ending "127.0.0.1<tab>localhost" reads as naming "localhos",
#      so the machine has no localhost at all. A line whose first character is
#      '#' is exempt from the chop and is skipped anyway, so an unterminated
#      final COMMENT is read whole and harms nothing; convergence still requires
#      the terminator there, because "the file ends terminated" is one property
#      a rebuild can guarantee and "the file ends terminated unless the last
#      line happens to be a comment" is not. The eaten character is not always a
#      loss: when it is a CARRIAGE RETURN the chop is what makes that line read
#      correctly, which is why handing it back is the one thing the rebuild must
#      not do there. See THE UNREAD CARRIAGE RETURN below.
#
#   5. A LINE LONGER THAN 4095 BYTES IS SEVERAL LINES TO THE RESOLVER, and this
#      script reads it as one. `_fsi_get_line` calls `fgets(s, 4096, fp)`, so a
#      longer line arrives in chunks and fact 4's chop then eats the last byte
#      of EVERY chunk. Measured: a 4200-byte name parses as two records there
#      and one line here. Nothing is done about it, and nothing can be while
#      lines are read into shell variables; it is recorded because this section
#      is where the divergences live and an unrecorded one gets rediscovered.
#      The pin's own fields cannot reach that length (they are single columns
#      from the YAML), so this bounds what the FILTER may misjudge on somebody
#      else's line, not what this script writes.
#
# INSTALL is atomic: chmod/chown the temp file to the target's own mode and
# owner, then rename it INTO the target path. mktemp creates the temp beside the
# target so the rename never crosses filesystems, and that LOCATION is pinned by
# pointing the seam at a directory the test cannot write: the refusal must be
# "no temporary file could be created beside it", which a temp made anywhere
# else never produces. Both halves of the metadata copy are pinned too, the mode
# directly and the owner through the target's GROUP, which the temp does not
# inherit because a new file takes its DIRECTORY's group on macOS. The old
# `cat "$tmp" > target` kept the inode but TRUNCATED first, so a failure
# mid-write left an EMPTY /etc/hosts and still exited 0. The rename trades the
# inode away (a watcher pinning the vnode must re-open) for never exposing a
# partial file. A SYMLINKED target is followed to its referent and the referent
# is what gets replaced, so the operator's indirection survives and the file the
# resolver actually reads is the one that changes; metadata is read from the
# referent too, because a symlink's own mode is 0755 on macOS and means nothing.
#
# FAILURE IS CHECKED, NEVER INFERRED. Every step that can fail has its status
# tested at the call site rather than left to `set -e`, because the interpreter
# that runs this as root is chosen by PATH (see INTERPRETER below) and the two
# candidates disagree about when a failed redirect aborts a function. That
# disagreement already cost this file a fail-open: a `while ... done <"$path"`
# followed by a `printf` reported an UNREADABLE hosts file as an EMPTY one, so
# the rebuild collapsed to the pin record alone, with a success message and exit
# 0 under bash 3.2. Moving the redirect onto a GROUP whose status is tested,
# `{ ... } <"$path" || return 1`, is what fixes that. The trailing `:` inside
# those groups is not what makes today's code correct and no test can tell it
# apart: it pins the group's status to the redirect instead of inheriting it
# from whatever the loop body last returned, which is 0 today only because both
# bodies happen to end in an `if`. It is there so a later edit to a body cannot
# turn a successful read into a refusal, or a failed one into a success, without
# anyone noticing. That is the exact accident being fixed here, one edit later.
#
# THE TEMPORARY FILE is removed by an EXIT trap plus one explicit handler per
# signal in CLEANED_UP_SIGNAL_NAMES. test/integration/tailnet-pins.sh keeps its
# OWN copy of that list, diffs the two and names any member that appears in one
# and not the other, then drives its per-signal cases from the list this file
# declares rather than from a literal of its own, so a member cannot be added or
# dropped here without the suite saying which one. What the list is NOT is six
# load-bearing handlers, and the previous wording ("every member is exercised")
# implied more than the suite could show. Measured on this host, deleting the
# per-signal handlers changes the outcome for three: INT (both interpreters exit
# 0 and the target is rewritten), QUIT (bash 3.2 leaves a temporary file behind,
# bash 5.3 exits 0 and rewrites the target) and a write-triggered XFSZ (bash 5.3
# leaves a temporary file behind). HUP, TERM and PIPE behave identically with
# and without a handler here; they stay in the list because WHICH fatal signals
# let the EXIT trap run first is a property of the interpreter, and sudo picks
# the interpreter by PATH. The EXIT trap alone is NOT enough, which is what this
# comment used to claim: the QUIT and XFSZ leaks above are what that claim cost.
# SIGKILL and SIGSTOP cannot be trapped by any process, so those two can still
# leave the temporary file behind; nothing here prevents that.
#
# INTERPRETER. Both bash 3.2 and bash 5.3 run this, so neither is assumed. sudo
# on this machine sets no secure_path and passes the invoking PATH through, so
# `sudo ... bash` resolves to whatever comes first there: measured
# `sudo -n /usr/bin/env bash -c 'echo $BASH_VERSION $BASH'` -> 5.3.15 from
# /opt/homebrew/bin/bash at uid 0, while a PATH without Homebrew resolves
# /bin/bash 3.2.57. No associative arrays and no mapfile, so 3.2 stays
# supported, and no safety decision rests on errexit, because the two versions
# do not agree about it.
#
# KNOWN LIMITATION, CRLF. hosts(5) on this machine says items are separated by
# blanks and tabs, so a carriage return is NOT a field separator and this script
# does not treat one as a field boundary. A TERMINATED record written with CRLF
# line endings therefore claims the name "pin<CR>", not "pin": it is neither
# dropped as the pin's nor counted toward convergence, so it survives while the
# file still reports as converged. That used to rest on an unmeasured guess
# about the resolver. It no longer does: `_fsi_tokenize` separates on " \t" and
# skips only ' ', '\t' and '\n', so a CR is an ordinary name character there
# too, and the resolver reads that record as naming "pin<CR>" exactly as this
# script does. The two AGREE, which is what makes leaving such a line alone
# correct rather than a coin flip. It is dead litter: measured, a lookup for the
# pin's name walks past it and is answered by the appended record, and in a file
# holding only that line the lookup finds nothing at all. The file converges on
# the next run and is not rewritten again, so the litter costs one rebuild
# rather than one per apply. Convert such a file to LF endings if you want the
# record gone.
#
# THE UNREAD CARRIAGE RETURN is the one on a FINAL line with no terminator, and
# it is not covered by the paragraph above. `_fsi_get_line` chops the last
# character of every non-comment line whether or not there is a newline to chop
# (fact 4), so there the character it eats is the CR ITSELF: the resolver reads
# "...localhost<CR>" as a clean "localhost" and "...pin<CR>" as a clean "pin".
# Such a CR is not litter. It is invisible, and every name on that line answers.
#
# WHICH MAKES THE TERMINATOR NORMALIZATION DANGEROUS ON EXACTLY THAT LINE, and
# an earlier pass shipped that danger. Adding the newline stops the chop landing
# on a real byte, which is the whole point when the byte is record content
# ("localhos" becomes "localhost" again). When the byte is a CR it is the
# reverse. Measured, both directions, with Apple's parser compiled verbatim:
# a file ending "127.0.0.1<TAB>localhost<CR>" answers localhost before the run
# and, with the CR handed back, answers NOTHING for localhost afterwards. The
# machine loses localhost, the loopback gate does not notice (it reads the
# ADDRESS field, and the address is still 127.0.0.1), the run reports success,
# and the next run reports "already converged", so the file is never revisited.
# It generalizes past localhost: "10.0.0.5<TAB>nas.home<CR>" as the final
# unterminated line answers 10.0.0.5 for nas.home before and nothing after.
#
# SO THAT LINE IS READ THE WAY THE RESOLVER READS IT. Both file walkers hand it
# to `hosts_line_without_unread_carriage_return` before anything else looks at
# it, which drops exactly the byte the resolver had already discarded, and the
# ordinary rules then apply to what is left. Three consequences, all measured:
# localhost and third-party names survive the rebuild; a STALE pin record
# sitting on that line now claims the pin's name and is DROPPED rather than
# left in the file; and after the run, EVERY NAME resolves the same as it does
# from the LF-terminated file with the same records, so the CR stops being a
# special case for what the machine reads.
#
# Not the same BYTES as that file, and the difference is worth naming so nobody
# reads more into the sentence above than was measured: the LF-terminated file
# may already be converged, in which case nothing is rewritten and its records
# keep their original order, while the unterminated one is rebuilt and its
# surviving records end up above the appended pin. That is the terminator
# condition doing its job, not the carriage return doing anything. Pinned in
# LAYER 2j4 of test/integration/tailnet-pins.sh and in P15 of
# test/unit/tailnet-pin-hosts-predicates.sh.
#
# WHY THE WIDER REPAIRS ARE STILL REFUSED. Two present themselves for the
# TERMINATED CRLF record above, and both were measured rather than argued.
# Stripping a trailing CR per field inside `hosts_line_claims_name`, and adding
# \r to HOSTS_ITEM_SEPARATOR_CHARACTERS, each make this script claim a THIRD
# PARTY's CRLF record: "10.0.0.5 nas.home pin<CR>" belongs to nas.home, the
# resolver answers 10.0.0.5 for that name and answers nothing for the pin's
# names from that line, and under either repair the rebuild drops it, so root
# deletes an unrelated record from /etc/hosts. That is the same trade refused
# for comment-borne names below, and refused for the same reason: a
# divergence-free filter is worth more than the removal of a line that answers
# nothing. Note what separates these from the unread CR above, because it is the
# whole distinction: there the resolver had ALREADY discarded the byte, so
# matching it changes no reading; here the resolver reads the CR, so discarding
# it invents a reading nothing has.
#
# The separator-set version is worse still, because both predicates read that
# set: "127.0.0.1<CR><TAB>localhost" would read as a valid loopback record here
# while `inet_pton` refuses that first token in the resolver, so THE LOOPBACK
# GATE would vouch for a file the machine has no localhost in. Measured: with \r
# in the set, a run over such a file rewrites it and exits 0 where it refuses
# today.
#
# WHAT THE GATE DOES ACCEPT, stated because the paragraph above used to read as
# though a CR could only ever reach the gate through one of those repairs. A
# TERMINATED "127.0.0.1<TAB>localhost<CR>" passes the gate TODAY, and honestly:
# the gate asks whether 127.0.0.1 maps to at least one name, the resolver reads
# that name as "localhost<CR>", and a name it is. That machine has no working
# localhost, before this script runs and after, and refusing to install would
# abort `chezmoi apply` over a file this script neither created nor worsened.
# The gate's latitude about WHICH name serves localhost (see THE LOOPBACK GATE)
# is the same latitude here. Both shapes are pinned, the refused one and the
# accepted one, in test/unit/tailnet-pin-hosts-predicates.sh
# (p1-carriage-return-in-address, p1-trailing-carriage-return-loopback,
# p2-crlf-third-party-short-name, p2-crlf-stale-pin-fqdn) and in LAYERS 2j3 and
# 2j4 of test/integration/tailnet-pins.sh.
#
# KNOWN LIMITATION, A NAME INSIDE COMMENT TEXT. This one is a real divergence,
# measured. Because every predicate reads `hosts_line_record_text`, a line like
# "10.0.0.5 nas.home # pin" does not read as claiming the pin's short name here,
# so the rebuild keeps it. The resolver reads that same line as mapping 10.0.0.5
# to the aliases "#" and "pin" (fact 2 above), and `_fsi_get_host` returns the
# FIRST matching record and stops reading the file, so such a line ABOVE the
# appended pin answers for the pin's name INSTEAD of the pin, while this script
# reports the file converged. Nothing here cleans that up. Matching the resolver
# in the filter would mean deleting root-owned records on the strength of
# comment text, a far larger blast radius than the gate's under-acceptance, so
# that change is deliberately not made in the same pass that measured it. Move
# the name out of the comment, or delete the line by hand.

# Shell options belong to the EXECUTED script. Sourcing this file (the unit
# suite does, to call its predicates one at a time) must define functions and
# change nothing else about the caller, so this is guarded on the same condition
# as the entry point at the bottom of the file.
if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
  set -euo pipefail
fi

readonly PROGRAM_NAME="${0##*/}"

# ---------------------------------------------------------------------------
# Named constants. Nothing below buries one of these in an expression.
# ---------------------------------------------------------------------------

# The file this reconciles, and the seam that redirects it. The seam exists so
# the test suite exercises THIS code against a fixture instead of a copy of it
# extracted with string surgery, which is how the old suite and the old
# implementation were able to drift. `sudo` resets the environment (env_reset),
# so the deployed invocation cannot be redirected through it.
readonly DEFAULT_HOSTS_FILE=/etc/hosts
readonly HOSTS_FILE_SEAM_VARIABLE_NAME='TAILNET_PIN_HOSTS_FILE'

# The three answers the seam can give. SET-BUT-EMPTY IS NOT UNSET: a plain
# `${VAR:-$DEFAULT}` reads an empty value as "not configured" and quietly aims a
# root-owned rewrite at the real /etc/hosts, which is precisely what a caller
# passing an empty path did not ask for. Three named states, so the empty case
# has somewhere to be refused instead of somewhere to hide.
readonly HOSTS_FILE_SEAM_ABSENT=absent
readonly HOSTS_FILE_SEAM_EMPTY=empty
readonly HOSTS_FILE_SEAM_PATH=path

# hosts(5): "A '#' indicates the beginning of a comment; characters up to the
# end of the line are not interpreted by routines which search the file." The
# routine that actually searches the file does not honour that (READING A HOSTS
# LINE, fact 2). This script honours the man page anyway, deliberately, and fact
# 3 says what that costs and buys.
readonly HOSTS_COMMENT_CHARACTER='#'

# hosts(5) and the resolver agree that a record is "Internet address / Official
# host name / Aliases", and `_fsi_parse_host` rejects outright below two tokens,
# so an address with no name after it maps nothing. Counted here over the
# COMMENT-STRIPPED text, which is the stricter reading.
readonly HOSTS_RECORD_MINIMUM_FIELD_COUNT=2

# What separates one hosts item from the next, taken from the resolver rather
# than from the man page: `_fsi_parse_host` tokenizes with " \t", and
# `_fsi_tokenize` additionally skips ' ', '\t' and '\n' before EVERY token,
# including the first. Used as IFS so this script splits a record into the same
# fields the resolver does, and so a leading run of blanks is skipped here for
# the same reason it is skipped there.
readonly HOSTS_ITEM_SEPARATOR_CHARACTERS=$' \t\n'

# The byte a CRLF file leaves at the end of every line. Named because it is read
# three different ways here: it is an ordinary NAME character to both this script
# and the resolver (KNOWN LIMITATION, CRLF), it is refused inside a pin's own
# fields, and on a final line with no terminator the resolver never reads it at
# all (THE UNREAD CARRIAGE RETURN).
readonly CARRIAGE_RETURN=$'\r'

# The address a working localhost record must map. See THE LOOPBACK GATE above
# for why the whole 127.0.0.0/8 block does not qualify.
readonly LOOPBACK_ADDRESS='127.0.0.1'

# Written between the columns of the record this script installs. hosts(5):
# "Items are separated by any number of blanks and/or tab characters."
readonly HOSTS_FIELD_SEPARATOR=$'\t'

# Characters a pin field may not contain. Space, tab, form feed and newline
# split one record into extra columns or extra LINES when the file is read, and
# # starts a hosts comment that truncates the record. Carriage return is in the
# set for a DIFFERENT reason and the old comment got this wrong: a CR does not
# split a record when this script reads a file (see KNOWN LIMITATION above), but
# a field carrying one would be written out as a name these same predicates then
# read as a different name, so the record could never converge and every apply
# would rewrite the file. Deliberately the same set the runner template refuses
# at render time (Go's \s class plus #), so a field that renders can never be
# refused here and vice versa. Other Unicode spaces (vertical tab, U+00A0,
# U+2003) are absent on purpose: none of them splits a hosts record, so none of
# them can smuggle a column, and neither check refuses them.
readonly HOSTS_COLUMN_FORBIDDEN_CHARACTERS=$' \t\n\r\f#'

# A file is converged when EXACTLY this many lines name the pin.
readonly CONVERGED_CLAIMING_LINE_COUNT=1

readonly BOOLEAN_TRUE=1
readonly BOOLEAN_FALSE=0

# Bound on how far a symlinked hosts path is followed, so a link loop refuses
# instead of spinning.
readonly MAXIMUM_SYMLINK_HOPS=8

readonly EXIT_STATUS_OK=0
readonly EXIT_STATUS_REFUSED=1
readonly EXIT_STATUS_USAGE=2

# What the shell itself reports for a process killed by signal N, and therefore
# what this script reports for one it cleaned up after. See finish_after_signal.
readonly SIGNAL_EXIT_STATUS_BASE=128

# Signals after which the temporary file must not survive. This list IS the
# contract: test/integration/tailnet-pins.sh diffs it against its own copy and
# then drives its per-signal cases from it, so editing this line changes what
# runs and the suite reports the edit. Three of the six handlers are what change
# the outcome on this host; the rest are here because WHICH fatal signals let
# the EXIT trap run first differs between the two interpreters sudo may pick,
# and an assumed answer is how the leak this list exists for went unnoticed. See
# THE TEMPORARY FILE in the header for the measured per-signal breakdown.
# SIGKILL and SIGSTOP are absent because no process can trap them.
CLEANED_UP_SIGNAL_NAMES=(HUP INT QUIT TERM PIPE XFSZ)
readonly CLEANED_UP_SIGNAL_NAMES

readonly EXPECTED_ARGUMENT_COUNT=3

# ---------------------------------------------------------------------------
# Reporting. The one place a message reaches the operator.
# ---------------------------------------------------------------------------

report() { # <message>
  printf '%s: %s\n' "$PROGRAM_NAME" "$*"
}

refuse() { # <message>
  printf '%s: %s\n' "$PROGRAM_NAME" "$*" >&2
  exit "$EXIT_STATUS_REFUSED"
}

# How every message names the file being reconciled. A refusal that names
# /etc/hosts and a success that names /etc/hosts.real are two reports about the
# same operation that read as two different files, so when a symlink chain moves
# the real file the operator is told both paths, always, in both directions.
hosts_file_description() { # <configured-path> <resolved-path>
  local configured_path=$1 resolved_path=$2
  if [[ $configured_path == "$resolved_path" ]]; then
    printf '%s\n' "$configured_path"
  else
    printf '%s (resolved through its symlink chain to %s)\n' \
      "$configured_path" "$resolved_path"
  fi
}

# ---------------------------------------------------------------------------
# Pure predicates and accessors: one question each, no side effects, no I/O.
# Each is callable and testable on its own, which the old inline grep was not.
# ---------------------------------------------------------------------------

# The part of <line> that carries the record: everything before the first
# comment character. The one place comment text is cut, so both predicates below
# read the same text and the divergence that cut creates has one home and one
# set of tests. See READING A HOSTS LINE, fact 3.
#
# It writes into the caller's <destination-variable> instead of printing,
# because printing would fork a subshell per line per predicate on every file
# walk, and this runs as root over the whole of /etc/hosts.
hosts_line_record_text() { # <destination-variable> <line>
  printf -v "$1" '%s' "${2%%"${HOSTS_COMMENT_CHARACTER}"*}"
}

# The line, minus the carriage return the resolver never read. ONLY ever called
# on a file's FINAL line when that file has no terminator, which is the only
# place such a byte exists; the two file walkers are the only callers, because
# they are the only code that knows a line is that line.
#
# `_fsi_get_line` chops the last byte of every non-comment line whether or not
# there is a newline to chop (READING A HOSTS LINE, fact 4), so on that one line
# the resolver reads one byte less than the file holds. The rebuild gives that
# byte back when it writes the terminator. Giving back a byte of the RECORD is
# the repair fact 4 exists for ("localhos" becomes "localhost" again). Giving
# back a CR is not: it is a line-ending artifact the resolver had already
# discarded, and handing it back turns a name the machine resolves into one it
# cannot. So exactly that byte, and only when it is a CR, is dropped here, and
# the rest of the line is passed through untouched. See THE UNREAD CARRIAGE
# RETURN in the header for the measurement and for what the two alternatives
# cost.
#
# The '#' exemption mirrors `_fsi_get_line`'s own (`if (s[0] != '#')`): a final
# unterminated COMMENT is not chopped there, so its CR was read, not unread, and
# removing it would be an edit to a line this rebuild promises to copy through.
#
# Writes into the caller's <destination-variable> for the same reason
# hosts_line_record_text does: printing would fork a subshell per line.
#
# NO LOCALS, and that is a correctness requirement rather than brevity. `local`
# is DYNAMICALLY scoped in bash, so a local named for what this holds would
# shadow the caller's variable of the same name and `printf -v` would then write
# to the shadow. Both callers pass a variable named `line`, so a `local line`
# here silently made this function a no-op from their side. Same reason
# hosts_line_record_text declares none.
hosts_line_without_unread_carriage_return() { # <destination-variable> <line>
  if [[ $2 != "$HOSTS_COMMENT_CHARACTER"* && $2 == *"$CARRIAGE_RETURN" ]]; then
    printf -v "$1" '%s' "${2%"$CARRIAGE_RETURN"}"
  else
    printf -v "$1" '%s' "$2"
  fi
}

# Is this line a record mapping exactly <address> to at least one name?
#
# Two conditions, and both matter. Once comment text is removed the line must
# carry at least an address and one name (the old gate skipped this, so a
# comment-only "127.0.0.1  # decoy" passed as a loopback record), and the
# address must be the FIRST FIELD.
#
# First field, NOT first character. The resolver skips leading blanks before the
# first token, so "  127.0.0.1 localhost" is a working localhost record and a
# gate refusing it would refuse a file the machine resolves fine; this predicate
# used to refuse one, on the stated grounds that the question was unmeasured. It
# is measured now (READING A HOSTS LINE, fact 1). The first-FIELD half is
# what still refuses "10.0.0.1<tab>127.0.0.1", where the address is a NAME.
hosts_line_is_record_for_address() { # <line> <address>
  local line=$1 address=$2 record_text
  hosts_line_record_text record_text "$line"
  local -a fields=()
  # Split on the separators the resolver uses, so `fields[0]` is the first field
  # here for the same reason it is there, and a leading run of blanks is skipped
  # in both. `read -r -a` splits WITHOUT globbing, so a '*' in a hosts file
  # stays literal text with no reliance on the shell's noglob state.
  local IFS=$HOSTS_ITEM_SEPARATOR_CHARACTERS
  read -r -a fields <<<"$record_text"
  ((${#fields[@]} >= HOSTS_RECORD_MINIMUM_FIELD_COUNT)) || return 1
  [[ ${fields[0]} == "$address" ]]
}

# Is this line a record a machine can resolve localhost through?
hosts_line_is_valid_loopback_record() { # <line>
  hosts_line_is_record_for_address "$1" "$LOOPBACK_ADDRESS"
}

# Does this line claim <name> as one of its host names? Name fields are the
# columns AFTER the address, with comment text stripped. Field equality, so a
# different host whose name merely contains this one is not a claim. Leading
# blanks do not hide a claim, for the same reason they do not hide a record.
#
# This is the predicate the comment-stripping divergence UNDER-serves: the
# resolver would read a name written after a '#' as a real alias and this does
# not, so such a line survives the rebuild. See KNOWN LIMITATION, A NAME INSIDE
# COMMENT TEXT.
hosts_line_claims_name() { # <line> <name>
  local line=$1 name=$2 record_text
  hosts_line_record_text record_text "$line"
  local -a fields=()
  local IFS=$HOSTS_ITEM_SEPARATOR_CHARACTERS
  read -r -a fields <<<"$record_text"
  ((${#fields[@]} >= HOSTS_RECORD_MINIMUM_FIELD_COUNT)) || return 1
  local index
  for ((index = 1; index < ${#fields[@]}; index++)); do
    if [[ ${fields[index]} == "$name" ]]; then
      return 0
    fi
  done
  return 1
}

# Does this line claim either of the two names this pin owns?
hosts_line_is_claimed_by_pin() { # <line> <fqdn> <short>
  local line=$1 fqdn=$2 short=$3
  hosts_line_claims_name "$line" "$fqdn" || hosts_line_claims_name "$line" "$short"
}

# Is this value usable as exactly one hosts column?
is_single_hosts_column() { # <value>
  local value=$1
  [[ -n $value ]] || return 1
  [[ $value != *["$HOSTS_COLUMN_FORBIDDEN_CHARACTERS"]* ]]
}

# The one canonical record this pin converges on. A CONSTANT printf format, so
# a '%' inside pin data is data and never a directive.
pin_record_line() { # <ip> <fqdn> <short>
  printf '%s%s%s%s%s\n' \
    "$1" "$HOSTS_FIELD_SEPARATOR" "$2" "$HOSTS_FIELD_SEPARATOR" "$3"
}

# Is the file converged, given what the survey found?
#
# The terminator is a convergence condition, not a cosmetic one, and it is the
# one only the rebuild can satisfy. A file the resolver reads differently from
# its bytes (READING A HOSTS LINE, fact 4) is not a file this script may report
# success over, and the converged path is the only path that reports success
# without rebuilding.
pin_is_converged() { # <claiming-line-count> <desired-record-present> <file-ends-with-terminator>
  local claiming_line_count=$1 desired_record_present=$2
  local file_ends_with_terminator=$3
  [[ $claiming_line_count -eq $CONVERGED_CLAIMING_LINE_COUNT ]] &&
    [[ $desired_record_present -eq $BOOLEAN_TRUE ]] &&
    [[ $file_ends_with_terminator -eq $BOOLEAN_TRUE ]]
}

# ---------------------------------------------------------------------------
# The hosts-path seam.
# ---------------------------------------------------------------------------

# Which of the three seam states is this run in? `${VAR+x}` answers SET (empty
# or not); `${VAR:-}` cannot, and conflating the two is what aims a root rewrite
# at the real /etc/hosts when a caller passes an empty path.
classify_hosts_file_seam() {
  if [[ -z ${TAILNET_PIN_HOSTS_FILE+x} ]]; then
    printf '%s\n' "$HOSTS_FILE_SEAM_ABSENT"
  elif [[ -z $TAILNET_PIN_HOSTS_FILE ]]; then
    printf '%s\n' "$HOSTS_FILE_SEAM_EMPTY"
  else
    printf '%s\n' "$HOSTS_FILE_SEAM_PATH"
  fi
}

# The path this run reconciles. Only ever called for the ABSENT and PATH states;
# the EMPTY state is refused by the caller before this is reached.
configured_hosts_file_path() {
  if [[ -z ${TAILNET_PIN_HOSTS_FILE+x} ]]; then
    printf '%s\n' "$DEFAULT_HOSTS_FILE"
  else
    printf '%s\n' "$TAILNET_PIN_HOSTS_FILE"
  fi
}

# ---------------------------------------------------------------------------
# Filesystem readers. No mutation.
# ---------------------------------------------------------------------------

# Follow a symlink chain to the file it finally names. Relative link targets
# resolve against the directory of the link that holds them.
resolve_symlink_chain() { # <path>
  local path=$1 hop=0 link_target
  while [[ -L $path ]]; do
    hop=$((hop + 1))
    if ((hop > MAXIMUM_SYMLINK_HOPS)); then
      return 1
    fi
    link_target=$(readlink "$path") || return 1
    case $link_target in
      /*) path=$link_target ;;
      *) path="$(dirname "$path")/$link_target" ;;
    esac
  done
  printf '%s\n' "$path"
}

# GNU stat (-c) is tried before BSD stat (-f) because GNU's -f means
# "filesystem status" and SUCCEEDS with useless output, so a BSD-first chain
# never falls through. GNU coreutils precedes the BSD tools on PATH inside the
# nix dev shell, so the order is load-bearing there, not theoretical. -L on
# both: metadata must describe the referent, never a symlink (whose own mode is
# 0755 on macOS and carries no intent).
read_file_mode() { # <path>
  stat -L -c '%a' "$1" 2>/dev/null || stat -L -f '%Lp' "$1"
}

read_file_owner() { # <path>
  stat -L -c '%u:%g' "$1" 2>/dev/null || stat -L -f '%u:%g' "$1"
}

# DETECTION. Reports
# "<claiming-line-count> <desired-record-present> <file-ends-with-terminator>"
# and changes nothing. Returns NONZERO and reports nothing when the source
# cannot be opened: a source that cannot be read is not an empty source, and
# treating it as one collapsed the rebuild to the pin record alone.
#
# An EMPTY file ends with a terminator by this accounting: it has no final line
# to be missing one, and answering NO there would send every run of an empty
# hosts file through a rebuild the loopback gate refuses anyway.
survey_hosts_file() { # <path> <fqdn> <short> <desired-record>
  local path=$1 fqdn=$2 short=$3 desired_record=$4
  local claiming_line_count=0 desired_record_present=$BOOLEAN_FALSE
  local file_ends_with_terminator=$BOOLEAN_TRUE line
  local line_is_the_unterminated_final_one=$BOOLEAN_FALSE
  # The `|| return 1` on the group is what refuses an unopenable source. The
  # trailing `:` pins the group's status to the REDIRECT rather than to whatever
  # the loop body last returned; see FAILURE IS CHECKED in the header for why it
  # is here even though nothing today can tell it apart.
  #
  # The `|| [[ -n $line ]]` half of the condition is what feeds an UNTERMINATED
  # final line to the body at all, and it is the ONLY place that fact can be
  # observed: one more `read` runs before the loop exits and clears `line`, so a
  # check after `done` always sees an empty one. Hence the assignment here. The
  # flag needs no reset per iteration: `read` fails only at end of file, so the
  # branch runs at most once and on the last line the body ever sees.
  #
  # That line is then read the way write_kept_hosts_lines will write it, which
  # is the way the RESOLVER reads it. Two walkers disagreeing about what the
  # last line of one file says is exactly the drift the convergence contract
  # exists to close.
  {
    while IFS= read -r line ||
      { [[ -n $line ]] && line_is_the_unterminated_final_one=$BOOLEAN_TRUE; }; do
      if ((line_is_the_unterminated_final_one == BOOLEAN_TRUE)); then
        file_ends_with_terminator=$BOOLEAN_FALSE
        hosts_line_without_unread_carriage_return line "$line"
      fi
      if hosts_line_is_claimed_by_pin "$line" "$fqdn" "$short"; then
        claiming_line_count=$((claiming_line_count + 1))
        if [[ $line == "$desired_record" ]]; then
          desired_record_present=$BOOLEAN_TRUE
        fi
      fi
    done
    :
  } <"$path" || return 1
  printf '%s %s %s\n' \
    "$claiming_line_count" "$desired_record_present" "$file_ends_with_terminator"
}

# VALIDATION. Does this file carry a record a machine can resolve localhost
# through? A file that cannot be opened answers NO, which is the safe direction
# for every caller (they refuse), and is stated here rather than accidental.
#
# The other two file walkers read a final unterminated line the way the resolver
# does (THE UNREAD CARRIAGE RETURN); this one does not, and does not need to.
# It is only ever pointed at the REBUILD, which terminates every line it writes,
# so there is no unterminated final line here to read either way. Point it at a
# source file and that stops being true.
hosts_file_has_valid_loopback_record() { # <path>
  local path=$1 line
  {
    while IFS= read -r line || [[ -n $line ]]; do
      if hosts_line_is_valid_loopback_record "$line"; then
        return 0
      fi
    done
  } <"$path"
  return 1
}

# ---------------------------------------------------------------------------
# Mutators.
# ---------------------------------------------------------------------------

# FILTERING. Drop every line the pin claims, copy everything else through
# unchanged. Nonzero when the source cannot be opened, when the destination
# cannot be opened, or when any single line fails to write: a half-copied
# rebuild is not a rebuild, and the gate that runs on the result would then be
# vouching for a truncated file.
#
# The final line of an UNTERMINATED source is the one exception to "unchanged",
# and it is deliberate in both halves: it gains the terminator (without which
# the appended record would join onto it), and it loses the carriage return the
# resolver never read there. See THE UNREAD CARRIAGE RETURN in the header.
write_kept_hosts_lines() { # <source> <destination> <fqdn> <short>
  local source_path=$1 destination_path=$2 fqdn=$3 short=$4
  local line line_is_the_unterminated_final_one=$BOOLEAN_FALSE
  {
    while IFS= read -r line ||
      { [[ -n $line ]] && line_is_the_unterminated_final_one=$BOOLEAN_TRUE; }; do
      if ((line_is_the_unterminated_final_one == BOOLEAN_TRUE)); then
        hosts_line_without_unread_carriage_return line "$line"
      fi
      if ! hosts_line_is_claimed_by_pin "$line" "$fqdn" "$short"; then
        printf '%s\n' "$line" || return 1
      fi
    done
    :
  } <"$source_path" >"$destination_path" || return 1
}

# APPENDING. The one correct record, last, on its own line.
append_hosts_record() { # <destination> <record>
  printf '%s\n' "$2" >>"$1"
}

# INSTALLATION. Metadata from the target, then an atomic rename onto it. Each
# step's status is tested here rather than left to the caller's errexit, which
# the two supported interpreters do not apply identically.
install_hosts_file_atomically() { # <source> <target>
  local source_path=$1 target_path=$2 mode owner
  mode=$(read_file_mode "$target_path") || return 1
  owner=$(read_file_owner "$target_path") || return 1
  chmod "$mode" "$source_path" || return 1
  chown "$owner" "$source_path" || return 1
  mv -f "$source_path" "$target_path" || return 1
}

# ---------------------------------------------------------------------------
# Temporary-file lifetime. Traps, not bail-only cleanup: the old body removed
# the temp on its explicit failure paths only, so a SIGTERM after mktemp left a
# mode-0600 hosts.XXXXXXXX beside the target, and the converged path ignored its
# own `rm` status and then hid the leftover behind `exit 0`.
# ---------------------------------------------------------------------------

temporary_hosts_file=

remove_temporary_hosts_file() {
  [[ -n $temporary_hosts_file ]] || return 0
  local path=$temporary_hosts_file
  temporary_hosts_file=
  [[ -e $path ]] || return 0
  if ! rm -f "$path"; then
    printf '%s: could not remove the temporary file %s; it is left behind\n' \
      "$PROGRAM_NAME" "$path" >&2
    return 1
  fi
}

# Clearing every trap first is what keeps `exit` from re-entering this handler,
# and what stops a second signal arriving mid-cleanup from starting a third.
finish() { # <exit-status>
  trap - EXIT "${CLEANED_UP_SIGNAL_NAMES[@]}"
  local status=$1
  remove_temporary_hosts_file || status=$EXIT_STATUS_REFUSED
  exit "$status"
}

# A signal-killed run must exit NONZERO. `$?` at the moment a signal arrives is
# the status of the last COMPLETED command, which is 0 far more often than not,
# so a handler forwarding it would turn a killed run into a reported success and
# the caller's `set -e` would carry on to the next pin. 128 + the signal number
# is what the shell itself reports when no handler runs, so trapping a signal
# does not change the status an operator sees. An unrecognized name falls back
# to the base alone, which is still nonzero.
finish_after_signal() { # <signal-name>
  local signal_number=0 reported_number
  reported_number=$(kill -l "$1" 2>/dev/null) || reported_number=
  if [[ $reported_number =~ ^[0-9]+$ ]]; then
    signal_number=$reported_number
  fi
  finish $((SIGNAL_EXIT_STATUS_BASE + signal_number))
}

install_temporary_file_traps() {
  trap 'finish "$?"' EXIT
  local signal_name
  for signal_name in "${CLEANED_UP_SIGNAL_NAMES[@]}"; do
    # shellcheck disable=SC2064  # the name must expand NOW: one trap is
    # installed per signal, each naming its own signal from a constant list.
    trap "finish_after_signal $signal_name" "$signal_name"
  done
}

# ---------------------------------------------------------------------------

main() {
  install_temporary_file_traps

  # Belt and braces for the mutating path: nothing here expands unquoted, and
  # the predicates split with `read -r -a` rather than the shell's splitting, so
  # this only matters if a future edit introduces an unquoted expansion.
  set -f

  if (($# != EXPECTED_ARGUMENT_COUNT)); then
    printf 'usage: %s <fqdn> <ip> <short>\n' "$PROGRAM_NAME" >&2
    exit "$EXIT_STATUS_USAGE"
  fi

  local fqdn=$1 ip=$2 short=$3

  local seam_state
  seam_state=$(classify_hosts_file_seam)
  if [[ $seam_state == "$HOSTS_FILE_SEAM_EMPTY" ]]; then
    refuse "refusing to edit any hosts file: $HOSTS_FILE_SEAM_VARIABLE_NAME is set but EMPTY, which is not the same as unset; unset it to reconcile $DEFAULT_HOSTS_FILE, or give it a path"
  fi
  local configured_hosts_file
  configured_hosts_file=$(configured_hosts_file_path)

  # The runner template refuses these at render time. Re-checked here because
  # this script is a standalone component with its own contract, and because a
  # field that is not one column would write extra columns, or extra LINES, into
  # a file being rewritten as root.
  local field_name field_value
  for field_name in fqdn ip short; do
    case $field_name in
      fqdn) field_value=$fqdn ;;
      ip) field_value=$ip ;;
      short) field_value=$short ;;
    esac
    if ! is_single_hosts_column "$field_value"; then
      refuse "refusing to edit $configured_hosts_file: pin $field_name is not a single hosts column"
    fi
  done

  local resolved_hosts_file
  if ! resolved_hosts_file=$(resolve_symlink_chain "$configured_hosts_file"); then
    refuse "refusing to edit $configured_hosts_file for $fqdn: its symlink chain does not resolve"
  fi
  local hosts_file_label
  hosts_file_label=$(hosts_file_description "$configured_hosts_file" "$resolved_hosts_file")
  if [[ ! -f $resolved_hosts_file ]]; then
    refuse "refusing to edit $hosts_file_label for $fqdn: the file is missing"
  fi

  local desired_record
  desired_record=$(pin_record_line "$ip" "$fqdn" "$short")

  local survey claiming_line_count desired_record_present
  local file_ends_with_terminator
  if ! survey=$(survey_hosts_file \
    "$resolved_hosts_file" "$fqdn" "$short" "$desired_record"); then
    refuse "refusing to edit $hosts_file_label for $fqdn: it could not be read, and an unreadable hosts file is not an empty one"
  fi
  read -r claiming_line_count desired_record_present file_ends_with_terminator \
    <<<"$survey"

  if pin_is_converged "$claiming_line_count" "$desired_record_present" \
    "$file_ends_with_terminator"; then
    report "MagicDNS fallback pin $fqdn already converged in $hosts_file_label"
    exit "$EXIT_STATUS_OK"
  fi

  if ! temporary_hosts_file=$(mktemp "$resolved_hosts_file.XXXXXXXX"); then
    refuse "refusing to rewrite $hosts_file_label for $fqdn: no temporary file could be created beside it"
  fi
  if ! write_kept_hosts_lines \
    "$resolved_hosts_file" "$temporary_hosts_file" "$fqdn" "$short"; then
    refuse "refusing to rewrite $hosts_file_label for $fqdn: reading it or writing the rebuild failed, and a partial rebuild is not a rebuild"
  fi

  # THE GATE, on the KEPT lines and before this script's own record joins them.
  if ! hosts_file_has_valid_loopback_record "$temporary_hosts_file"; then
    refuse "refusing to rewrite $hosts_file_label for $fqdn: the filtered result lost its loopback entry (no line this rebuild KEEPS maps $LOOPBACK_ADDRESS to a name written before a #, so nothing is left for localhost to resolve through)"
  fi

  if ! append_hosts_record "$temporary_hosts_file" "$desired_record"; then
    refuse "refusing to rewrite $hosts_file_label for $fqdn: the pin record could not be appended to the rebuild"
  fi

  if ! install_hosts_file_atomically "$temporary_hosts_file" "$resolved_hosts_file"; then
    refuse "refusing to report success for $fqdn: installing the rebuilt $hosts_file_label failed"
  fi
  temporary_hosts_file=
  report "MagicDNS fallback pin $fqdn written to $hosts_file_label"
}

if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
  main "$@"
fi
